component:core:
- changed-files:
  - any-glob-to-any-file: ['src/core/*', 'src/core/**/*']

component:core:rosecommon:
- changed-files:
    - any-glob-to-any-file: [ 'src/rosecommon/*', 'src/rosecommon/**/*' ]

component:server:character:
- changed-files:
    - any-glob-to-any-file: [ 'src/char/*', 'src/char/**/*' ]

component:server:login:
- changed-files:
    - any-glob-to-any-file: [ 'src/login/*', 'src/login/**/*' ]

component:server:map:
- changed-files:
    - any-glob-to-any-file: [ 'src/map/*', 'src/map/**/*' ]

component:server:node:
- changed-files:
    - any-glob-to-any-file: [ 'src/node/*', 'src/node/**/*' ]

component:databases:SQL:
- changed-files:
    - any-glob-to-any-file: [ 'Database/*.sql', 'Database/**/*.sql' ]

component:scripting:
- changed-files:
    - any-glob-to-any-file: [ 'scripts/*.lua', 'scripts/**/*.lua' ]

component:buildsystem:
- changed-files:
    - any-glob-to-any-file: [ 'cmake/*', 'cmake/**/*' ]

component:other:
- changed-files:
    - any-glob-to-any-file: [ 'src/tests/*', 'src/tests/**/*', 'src/bot/*', 'src/bot/**/*' ]
