registerNpc(801, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 90,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 18,
  hp                = 90,
  attack            = 10,
  hit               = 10,
  def               = 50,
  res               = 41,
  avoid             = 43,
  attack_spd        = 110,
  is_magic_damage   = 0,
  ai_type           = 151,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(802, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 95,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 21,
  hp                = 105,
  attack            = 10,
  hit               = 10,
  def               = 55,
  res               = 42,
  avoid             = 44,
  attack_spd        = 108,
  is_magic_damage   = 0,
  ai_type           = 151,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(803, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 100,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 24,
  hp                = 120,
  attack            = 10,
  hit               = 10,
  def               = 60,
  res               = 43,
  avoid             = 46,
  attack_spd        = 106,
  is_magic_damage   = 0,
  ai_type           = 151,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(804, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 105,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 27,
  hp                = 135,
  attack            = 10,
  hit               = 10,
  def               = 65,
  res               = 44,
  avoid             = 47,
  attack_spd        = 104,
  is_magic_damage   = 0,
  ai_type           = 151,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(805, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 110,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 30,
  hp                = 150,
  attack            = 10,
  hit               = 10,
  def               = 70,
  res               = 45,
  avoid             = 48,
  attack_spd        = 102,
  is_magic_damage   = 0,
  ai_type           = 151,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(806, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 124,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 35,
  hp                = 635,
  attack            = 10,
  hit               = 10,
  def               = 75,
  res               = 46,
  avoid             = 49,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 153,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(807, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 36,
  hp                = 690,
  attack            = 10,
  hit               = 10,
  def               = 80,
  res               = 47,
  avoid             = 50,
  attack_spd        = 98,
  is_magic_damage   = 0,
  ai_type           = 153,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(808, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 136,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 37,
  hp                = 745,
  attack            = 10,
  hit               = 10,
  def               = 85,
  res               = 48,
  avoid             = 51,
  attack_spd        = 96,
  is_magic_damage   = 0,
  ai_type           = 154,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(809, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 142,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 38,
  hp                = 800,
  attack            = 10,
  hit               = 10,
  def               = 90,
  res               = 49,
  avoid             = 52,
  attack_spd        = 94,
  is_magic_damage   = 0,
  ai_type           = 154,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(810, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 148,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 39,
  hp                = 855,
  attack            = 10,
  hit               = 10,
  def               = 95,
  res               = 51,
  avoid             = 53,
  attack_spd        = 92,
  is_magic_damage   = 0,
  ai_type           = 154,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end