registerNpc(801, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 90,
  l_weapon          = 0,
  level             = 0,
  hp                = 18,
  attack            = 90,
  hit               = 10,
  def               = 10,
  res               = 50,
  avoid             = 41,
  attack_spd        = 43,
  is_magic_damage   = 110,
  ai_type           = 0,
  give_exp          = 151,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(802, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 95,
  l_weapon          = 0,
  level             = 0,
  hp                = 21,
  attack            = 105,
  hit               = 10,
  def               = 10,
  res               = 55,
  avoid             = 42,
  attack_spd        = 44,
  is_magic_damage   = 108,
  ai_type           = 0,
  give_exp          = 151,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(803, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 100,
  l_weapon          = 0,
  level             = 0,
  hp                = 24,
  attack            = 120,
  hit               = 10,
  def               = 10,
  res               = 60,
  avoid             = 43,
  attack_spd        = 46,
  is_magic_damage   = 106,
  ai_type           = 0,
  give_exp          = 151,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(804, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 105,
  l_weapon          = 0,
  level             = 0,
  hp                = 27,
  attack            = 135,
  hit               = 10,
  def               = 10,
  res               = 65,
  avoid             = 44,
  attack_spd        = 47,
  is_magic_damage   = 104,
  ai_type           = 0,
  give_exp          = 151,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(805, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 110,
  l_weapon          = 0,
  level             = 0,
  hp                = 30,
  attack            = 150,
  hit               = 10,
  def               = 10,
  res               = 70,
  avoid             = 45,
  attack_spd        = 48,
  is_magic_damage   = 102,
  ai_type           = 0,
  give_exp          = 151,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(806, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 124,
  l_weapon          = 0,
  level             = 0,
  hp                = 35,
  attack            = 635,
  hit               = 10,
  def               = 10,
  res               = 75,
  avoid             = 46,
  attack_spd        = 49,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 153,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(807, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 36,
  attack            = 690,
  hit               = 10,
  def               = 10,
  res               = 80,
  avoid             = 47,
  attack_spd        = 50,
  is_magic_damage   = 98,
  ai_type           = 0,
  give_exp          = 153,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(808, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 136,
  l_weapon          = 0,
  level             = 0,
  hp                = 37,
  attack            = 745,
  hit               = 10,
  def               = 10,
  res               = 85,
  avoid             = 48,
  attack_spd        = 51,
  is_magic_damage   = 96,
  ai_type           = 0,
  give_exp          = 154,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(809, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 142,
  l_weapon          = 0,
  level             = 0,
  hp                = 38,
  attack            = 800,
  hit               = 10,
  def               = 10,
  res               = 90,
  avoid             = 49,
  attack_spd        = 52,
  is_magic_damage   = 94,
  ai_type           = 0,
  give_exp          = 154,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(810, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 148,
  l_weapon          = 0,
  level             = 0,
  hp                = 39,
  attack            = 855,
  hit               = 10,
  def               = 10,
  res               = 95,
  avoid             = 51,
  attack_spd        = 53,
  is_magic_damage   = 92,
  ai_type           = 0,
  give_exp          = 154,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end