registerNpc(461, {
  walk_speed        = 200,
  run_speed         = 480,
  scale             = 450,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 86,
  hp                = 81,
  attack            = 473,
  hit               = 236,
  def               = 424,
  res               = 202,
  avoid             = 107,
  attack_spd        = 95,
  is_magic_damage   = 0,
  ai_type           = 122,
  give_exp          = 218,
  drop_type         = 367,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 200,
  npc_type          = 10,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(462, {
  walk_speed        = 206,
  run_speed         = 491,
  scale             = 110,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 84,
  hp                = 39,
  attack            = 418,
  hit               = 211,
  def               = 361,
  res               = 139,
  avoid             = 133,
  attack_spd        = 95,
  is_magic_damage   = 0,
  ai_type           = 122,
  give_exp          = 88,
  drop_type         = 363,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 200,
  npc_type          = 7,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(463, {
  walk_speed        = 212,
  run_speed         = 503,
  scale             = 120,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 84,
  hp                = 39,
  attack            = 418,
  hit               = 211,
  def               = 361,
  res               = 139,
  avoid             = 133,
  attack_spd        = 95,
  is_magic_damage   = 0,
  ai_type           = 122,
  give_exp          = 89,
  drop_type         = 363,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 200,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(464, {
  walk_speed        = 218,
  run_speed         = 514,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 84,
  hp                = 39,
  attack            = 418,
  hit               = 211,
  def               = 361,
  res               = 139,
  avoid             = 133,
  attack_spd        = 95,
  is_magic_damage   = 0,
  ai_type           = 122,
  give_exp          = 89,
  drop_type         = 363,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 200,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(465, {
  walk_speed        = 224,
  run_speed         = 526,
  scale             = 140,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 94,
  hp                = 50,
  attack            = 434,
  hit               = 216,
  def               = 395,
  res               = 190,
  avoid             = 142,
  attack_spd        = 95,
  is_magic_damage   = 0,
  ai_type           = 122,
  give_exp          = 101,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 75,
  union_number      = 75,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 200,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(466, {
  walk_speed        = 230,
  run_speed         = 537,
  scale             = 150,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 104,
  hp                = 52,
  attack            = 484,
  hit               = 239,
  def               = 572,
  res               = 216,
  avoid             = 158,
  attack_spd        = 95,
  is_magic_damage   = 0,
  ai_type           = 122,
  give_exp          = 109,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 75,
  union_number      = 75,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 200,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(467, {
  walk_speed        = 236,
  run_speed         = 548,
  scale             = 160,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 114,
  hp                = 53,
  attack            = 536,
  hit               = 262,
  def               = 667,
  res               = 243,
  avoid             = 175,
  attack_spd        = 95,
  is_magic_damage   = 0,
  ai_type           = 122,
  give_exp          = 117,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 75,
  union_number      = 75,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 200,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end