registerNpc(461, {
  walk_speed        = 0,
  run_speed         = 200,
  scale             = 480,
  r_weapon          = 450,
  l_weapon          = 0,
  level             = 0,
  hp                = 86,
  attack            = 81,
  hit               = 473,
  def               = 236,
  res               = 424,
  avoid             = 202,
  attack_spd        = 107,
  is_magic_damage   = 95,
  ai_type           = 0,
  give_exp          = 122,
  drop_type         = 218,
  drop_money        = 367,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 200,
  hit_material_type = 10,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 17,
  height            = 0
});
registerNpc(462, {
  walk_speed        = 0,
  run_speed         = 206,
  scale             = 491,
  r_weapon          = 110,
  l_weapon          = 0,
  level             = 0,
  hp                = 84,
  attack            = 39,
  hit               = 418,
  def               = 211,
  res               = 361,
  avoid             = 139,
  attack_spd        = 133,
  is_magic_damage   = 95,
  ai_type           = 0,
  give_exp          = 122,
  drop_type         = 88,
  drop_money        = 363,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 200,
  hit_material_type = 7,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(463, {
  walk_speed        = 0,
  run_speed         = 212,
  scale             = 503,
  r_weapon          = 120,
  l_weapon          = 0,
  level             = 0,
  hp                = 84,
  attack            = 39,
  hit               = 418,
  def               = 211,
  res               = 361,
  avoid             = 139,
  attack_spd        = 133,
  is_magic_damage   = 95,
  ai_type           = 0,
  give_exp          = 122,
  drop_type         = 89,
  drop_money        = 363,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 200,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(464, {
  walk_speed        = 0,
  run_speed         = 218,
  scale             = 514,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 84,
  attack            = 39,
  hit               = 418,
  def               = 211,
  res               = 361,
  avoid             = 139,
  attack_spd        = 133,
  is_magic_damage   = 95,
  ai_type           = 0,
  give_exp          = 122,
  drop_type         = 89,
  drop_money        = 363,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 200,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(465, {
  walk_speed        = 0,
  run_speed         = 224,
  scale             = 526,
  r_weapon          = 140,
  l_weapon          = 0,
  level             = 0,
  hp                = 94,
  attack            = 50,
  hit               = 434,
  def               = 216,
  res               = 395,
  avoid             = 190,
  attack_spd        = 142,
  is_magic_damage   = 95,
  ai_type           = 0,
  give_exp          = 122,
  drop_type         = 101,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 75,
  sell_tab0         = 75,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 200,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(466, {
  walk_speed        = 0,
  run_speed         = 230,
  scale             = 537,
  r_weapon          = 150,
  l_weapon          = 0,
  level             = 0,
  hp                = 104,
  attack            = 52,
  hit               = 484,
  def               = 239,
  res               = 572,
  avoid             = 216,
  attack_spd        = 158,
  is_magic_damage   = 95,
  ai_type           = 0,
  give_exp          = 122,
  drop_type         = 109,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 75,
  sell_tab0         = 75,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 200,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(467, {
  walk_speed        = 0,
  run_speed         = 236,
  scale             = 548,
  r_weapon          = 160,
  l_weapon          = 0,
  level             = 0,
  hp                = 114,
  attack            = 53,
  hit               = 536,
  def               = 262,
  res               = 667,
  avoid             = 243,
  attack_spd        = 175,
  is_magic_damage   = 95,
  ai_type           = 0,
  give_exp          = 122,
  drop_type         = 117,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 75,
  sell_tab0         = 75,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 200,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end