registerNpc(8, {
  walk_speed        = 110,
  run_speed         = 150,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 1,
  hp                = 54,
  attack            = 1,
  hit               = 55,
  def               = 23,
  res               = 10,
  avoid             = 3,
  attack_spd        = 20,
  is_magic_damage   = 0,
  ai_type           = 91,
  give_exp          = 7,
  drop_type         = 100,
  drop_money        = 1,
  drop_item         = 40,
  union_number      = 40,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 150,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(9, {
  walk_speed        = 120,
  run_speed         = 160,
  scale             = 135,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 1,
  hp                = 54,
  attack            = 1,
  hit               = 55,
  def               = 23,
  res               = 10,
  avoid             = 4,
  attack_spd        = 20,
  is_magic_damage   = 0,
  ai_type           = 91,
  give_exp          = 7,
  drop_type         = 100,
  drop_money        = 1,
  drop_item         = 42,
  union_number      = 42,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 155,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(10, {
  walk_speed        = 130,
  run_speed         = 160,
  scale             = 140,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 2,
  hp                = 33,
  attack            = 1,
  hit               = 56,
  def               = 25,
  res               = 11,
  avoid             = 5,
  attack_spd        = 20,
  is_magic_damage   = 0,
  ai_type           = 91,
  give_exp          = 7,
  drop_type         = 100,
  drop_money        = 1,
  drop_item         = 45,
  union_number      = 45,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 160,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(316, {
  walk_speed        = 130,
  run_speed         = 280,
  scale             = 80,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 1,
  hp                = 94,
  attack            = 20,
  hit               = 70,
  def               = 500,
  res               = 500,
  avoid             = 500,
  attack_spd        = 15,
  is_magic_damage   = 0,
  ai_type           = 91,
  give_exp          = 4,
  drop_type         = 8,
  drop_money        = 1,
  drop_item         = 1,
  union_number      = 1,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 1,
  attack_range      = 100,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(317, {
  walk_speed        = 140,
  run_speed         = 300,
  scale             = 95,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 1,
  hp                = 94,
  attack            = 20,
  hit               = 70,
  def               = 500,
  res               = 500,
  avoid             = 500,
  attack_spd        = 15,
  is_magic_damage   = 0,
  ai_type           = 91,
  give_exp          = 4,
  drop_type         = 8,
  drop_money        = 1,
  drop_item         = 1,
  union_number      = 1,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 1,
  attack_range      = 100,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(318, {
  walk_speed        = 150,
  run_speed         = 310,
  scale             = 100,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 1,
  hp                = 94,
  attack            = 20,
  hit               = 70,
  def               = 500,
  res               = 500,
  avoid             = 500,
  attack_spd        = 15,
  is_magic_damage   = 0,
  ai_type           = 91,
  give_exp          = 4,
  drop_type         = 8,
  drop_money        = 1,
  drop_item         = 1,
  union_number      = 1,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 1,
  attack_range      = 100,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(811, {
  walk_speed        = 200,
  run_speed         = 450,
  scale             = 90,
  r_weapon          = 334,
  l_weapon          = 0,
  level             = 46,
  hp                = 1154,
  attack            = 131,
  hit               = 142,
  def               = 112,
  res               = 59,
  avoid             = 95,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 155,
  give_exp          = 34,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 30,
  sell_tab0         = 30,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 350,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(812, {
  walk_speed        = 210,
  run_speed         = 470,
  scale             = 96,
  r_weapon          = 334,
  l_weapon          = 0,
  level             = 47,
  hp                = 1177,
  attack            = 134,
  hit               = 144,
  def               = 115,
  res               = 60,
  avoid             = 97,
  attack_spd        = 102,
  is_magic_damage   = 0,
  ai_type           = 155,
  give_exp          = 38,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 30,
  sell_tab0         = 30,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 350,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(813, {
  walk_speed        = 220,
  run_speed         = 490,
  scale             = 102,
  r_weapon          = 334,
  l_weapon          = 0,
  level             = 48,
  hp                = 1200,
  attack            = 137,
  hit               = 146,
  def               = 117,
  res               = 61,
  avoid             = 98,
  attack_spd        = 104,
  is_magic_damage   = 0,
  ai_type           = 155,
  give_exp          = 41,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 31,
  sell_tab0         = 31,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 350,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(814, {
  walk_speed        = 230,
  run_speed         = 510,
  scale             = 108,
  r_weapon          = 334,
  l_weapon          = 0,
  level             = 49,
  hp                = 1224,
  attack            = 140,
  hit               = 148,
  def               = 120,
  res               = 62,
  avoid             = 100,
  attack_spd        = 106,
  is_magic_damage   = 0,
  ai_type           = 155,
  give_exp          = 45,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 31,
  sell_tab0         = 31,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 350,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(815, {
  walk_speed        = 240,
  run_speed         = 530,
  scale             = 114,
  r_weapon          = 334,
  l_weapon          = 0,
  level             = 50,
  hp                = 1248,
  attack            = 143,
  hit               = 150,
  def               = 123,
  res               = 64,
  avoid             = 102,
  attack_spd        = 108,
  is_magic_damage   = 0,
  ai_type           = 155,
  give_exp          = 49,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 32,
  sell_tab0         = 32,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 350,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(816, {
  walk_speed        = 250,
  run_speed         = 550,
  scale             = 120,
  r_weapon          = 334,
  l_weapon          = 0,
  level             = 51,
  hp                = 1272,
  attack            = 146,
  hit               = 152,
  def               = 125,
  res               = 65,
  avoid             = 103,
  attack_spd        = 110,
  is_magic_damage   = 0,
  ai_type           = 155,
  give_exp          = 53,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 32,
  sell_tab0         = 32,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 350,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(817, {
  walk_speed        = 260,
  run_speed         = 570,
  scale             = 126,
  r_weapon          = 334,
  l_weapon          = 0,
  level             = 52,
  hp                = 1296,
  attack            = 149,
  hit               = 154,
  def               = 128,
  res               = 66,
  avoid             = 105,
  attack_spd        = 112,
  is_magic_damage   = 0,
  ai_type           = 155,
  give_exp          = 57,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 33,
  sell_tab0         = 33,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 350,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(818, {
  walk_speed        = 270,
  run_speed         = 590,
  scale             = 132,
  r_weapon          = 334,
  l_weapon          = 0,
  level             = 53,
  hp                = 1320,
  attack            = 152,
  hit               = 156,
  def               = 131,
  res               = 67,
  avoid             = 107,
  attack_spd        = 114,
  is_magic_damage   = 0,
  ai_type           = 155,
  give_exp          = 61,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 33,
  sell_tab0         = 33,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 350,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(819, {
  walk_speed        = 280,
  run_speed         = 610,
  scale             = 138,
  r_weapon          = 334,
  l_weapon          = 0,
  level             = 54,
  hp                = 1344,
  attack            = 156,
  hit               = 158,
  def               = 133,
  res               = 69,
  avoid             = 109,
  attack_spd        = 116,
  is_magic_damage   = 0,
  ai_type           = 155,
  give_exp          = 65,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 34,
  sell_tab0         = 34,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 350,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(820, {
  walk_speed        = 290,
  run_speed         = 630,
  scale             = 144,
  r_weapon          = 334,
  l_weapon          = 0,
  level             = 55,
  hp                = 1368,
  attack            = 159,
  hit               = 161,
  def               = 136,
  res               = 70,
  avoid             = 110,
  attack_spd        = 118,
  is_magic_damage   = 0,
  ai_type           = 155,
  give_exp          = 69,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 34,
  sell_tab0         = 34,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 350,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end