registerNpc(309, {
  walk_speed        = 0,
  run_speed         = 200,
  scale             = 400,
  r_weapon          = 120,
  l_weapon          = 1081,
  level             = 0,
  hp                = 40,
  attack            = 21,
  hit               = 179,
  def               = 112,
  res               = 115,
  avoid             = 74,
  attack_spd        = 63,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 286,
  drop_type         = 38,
  drop_money        = 0,
  drop_item         = 30,
  union_number      = 30,
  need_summon_count = 60,
  sell_tab0         = 60,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1200,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(310, {
  walk_speed        = 0,
  run_speed         = 200,
  scale             = 450,
  r_weapon          = 130,
  l_weapon          = 1081,
  level             = 0,
  hp                = 60,
  attack            = 23,
  hit               = 269,
  def               = 146,
  res               = 174,
  avoid             = 119,
  attack_spd        = 90,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 286,
  drop_type         = 48,
  drop_money        = 0,
  drop_item         = 40,
  union_number      = 40,
  need_summon_count = 60,
  sell_tab0         = 60,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1200,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(311, {
  walk_speed        = 0,
  run_speed         = 200,
  scale             = 500,
  r_weapon          = 140,
  l_weapon          = 1081,
  level             = 0,
  hp                = 80,
  attack            = 26,
  hit               = 364,
  def               = 183,
  res               = 242,
  avoid             = 169,
  attack_spd        = 120,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 286,
  drop_type         = 60,
  drop_money        = 0,
  drop_item         = 50,
  union_number      = 50,
  need_summon_count = 60,
  sell_tab0         = 60,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1250,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(312, {
  walk_speed        = 0,
  run_speed         = 200,
  scale             = 550,
  r_weapon          = 150,
  l_weapon          = 1081,
  level             = 0,
  hp                = 100,
  attack            = 28,
  hit               = 464,
  def               = 223,
  res               = 427,
  avoid             = 225,
  attack_spd        = 151,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 286,
  drop_type         = 71,
  drop_money        = 0,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 60,
  sell_tab0         = 60,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1250,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(313, {
  walk_speed        = 0,
  run_speed         = 200,
  scale             = 600,
  r_weapon          = 160,
  l_weapon          = 1081,
  level             = 0,
  hp                = 120,
  attack            = 29,
  hit               = 568,
  def               = 265,
  res               = 535,
  avoid             = 286,
  attack_spd        = 185,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 286,
  drop_type         = 82,
  drop_money        = 0,
  drop_item         = 70,
  union_number      = 70,
  need_summon_count = 60,
  sell_tab0         = 60,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1300,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end