registerNpc(309, {
  walk_speed        = 200,
  run_speed         = 400,
  scale             = 120,
  r_weapon          = 1081,
  l_weapon          = 0,
  level             = 40,
  hp                = 21,
  attack            = 179,
  hit               = 112,
  def               = 115,
  res               = 74,
  avoid             = 63,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 286,
  give_exp          = 38,
  drop_type         = 0,
  drop_money        = 30,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1200,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(310, {
  walk_speed        = 200,
  run_speed         = 450,
  scale             = 130,
  r_weapon          = 1081,
  l_weapon          = 0,
  level             = 60,
  hp                = 23,
  attack            = 269,
  hit               = 146,
  def               = 174,
  res               = 119,
  avoid             = 90,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 286,
  give_exp          = 48,
  drop_type         = 0,
  drop_money        = 40,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1200,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(311, {
  walk_speed        = 200,
  run_speed         = 500,
  scale             = 140,
  r_weapon          = 1081,
  l_weapon          = 0,
  level             = 80,
  hp                = 26,
  attack            = 364,
  hit               = 183,
  def               = 242,
  res               = 169,
  avoid             = 120,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 286,
  give_exp          = 60,
  drop_type         = 0,
  drop_money        = 50,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1250,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(312, {
  walk_speed        = 200,
  run_speed         = 550,
  scale             = 150,
  r_weapon          = 1081,
  l_weapon          = 0,
  level             = 100,
  hp                = 28,
  attack            = 464,
  hit               = 223,
  def               = 427,
  res               = 225,
  avoid             = 151,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 286,
  give_exp          = 71,
  drop_type         = 0,
  drop_money        = 60,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1250,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(313, {
  walk_speed        = 200,
  run_speed         = 600,
  scale             = 160,
  r_weapon          = 1081,
  l_weapon          = 0,
  level             = 120,
  hp                = 29,
  attack            = 568,
  hit               = 265,
  def               = 535,
  res               = 286,
  avoid             = 185,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 286,
  give_exp          = 82,
  drop_type         = 0,
  drop_money        = 70,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1300,
  npc_type          = 1,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end