registerNpc(252, {
  walk_speed        = 160,
  run_speed         = 370,
  scale             = 105,
  r_weapon          = 1079,
  l_weapon          = 0,
  level             = 75,
  hp                = 25,
  attack            = 310,
  hit               = 174,
  def               = 165,
  res               = 266,
  avoid             = 112,
  attack_spd        = 100,
  is_magic_damage   = 1,
  ai_type           = 98,
  give_exp          = 55,
  drop_type         = 0,
  drop_money        = 1,
  drop_item         = 45,
  union_number      = 45,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 800,
  npc_type          = 7,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(384, {
  walk_speed        = 230,
  run_speed         = 700,
  scale             = 100,
  r_weapon          = 1079,
  l_weapon          = 0,
  level             = 110,
  hp                = 29,
  attack            = 469,
  hit               = 244,
  def               = 477,
  res               = 411,
  avoid             = 168,
  attack_spd        = 100,
  is_magic_damage   = 1,
  ai_type           = 146,
  give_exp          = 75,
  drop_type         = 389,
  drop_money        = 50,
  drop_item         = 30,
  union_number      = 30,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1350,
  npc_type          = 7,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(385, {
  walk_speed        = 250,
  run_speed         = 700,
  scale             = 100,
  r_weapon          = 1079,
  l_weapon          = 0,
  level             = 127,
  hp                = 44,
  attack            = 551,
  hit               = 294,
  def               = 614,
  res               = 489,
  avoid             = 197,
  attack_spd        = 105,
  is_magic_damage   = 1,
  ai_type           = 146,
  give_exp          = 105,
  drop_type         = 0,
  drop_money        = 57,
  drop_item         = 32,
  union_number      = 32,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1400,
  npc_type          = 7,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(386, {
  walk_speed        = 280,
  run_speed         = 700,
  scale             = 100,
  r_weapon          = 1079,
  l_weapon          = 0,
  level             = 131,
  hp                = 44,
  attack            = 571,
  hit               = 304,
  def               = 649,
  res               = 508,
  avoid             = 204,
  attack_spd        = 110,
  is_magic_damage   = 1,
  ai_type           = 146,
  give_exp          = 110,
  drop_type         = 0,
  drop_money        = 65,
  drop_item         = 33,
  union_number      = 33,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1500,
  npc_type          = 7,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(387, {
  walk_speed        = 280,
  run_speed         = 610,
  scale             = 182,
  r_weapon          = 1079,
  l_weapon          = 0,
  level             = 125,
  hp                = 43,
  attack            = 541,
  hit               = 289,
  def               = 597,
  res               = 480,
  avoid             = 194,
  attack_spd        = 110,
  is_magic_damage   = 1,
  ai_type           = 272,
  give_exp          = 106,
  drop_type         = 279,
  drop_money        = 20,
  drop_item         = 50,
  union_number      = 50,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1500,
  npc_type          = 7,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(388, {
  walk_speed        = 280,
  run_speed         = 610,
  scale             = 190,
  r_weapon          = 1079,
  l_weapon          = 0,
  level             = 135,
  hp                = 45,
  attack            = 590,
  hit               = 314,
  def               = 686,
  res               = 527,
  avoid             = 211,
  attack_spd        = 110,
  is_magic_damage   = 1,
  ai_type           = 272,
  give_exp          = 114,
  drop_type         = 279,
  drop_money        = 20,
  drop_item         = 50,
  union_number      = 50,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1500,
  npc_type          = 7,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end