registerNpc(252, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 370,
  r_weapon          = 105,
  l_weapon          = 1079,
  level             = 0,
  hp                = 75,
  attack            = 25,
  hit               = 310,
  def               = 174,
  res               = 165,
  avoid             = 266,
  attack_spd        = 112,
  is_magic_damage   = 100,
  ai_type           = 1,
  give_exp          = 98,
  drop_type         = 55,
  drop_money        = 0,
  drop_item         = 1,
  union_number      = 1,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 800,
  hit_material_type = 7,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 14,
  height            = 0
});
registerNpc(384, {
  walk_speed        = 0,
  run_speed         = 230,
  scale             = 700,
  r_weapon          = 100,
  l_weapon          = 1079,
  level             = 0,
  hp                = 110,
  attack            = 29,
  hit               = 469,
  def               = 244,
  res               = 477,
  avoid             = 411,
  attack_spd        = 168,
  is_magic_damage   = 100,
  ai_type           = 1,
  give_exp          = 146,
  drop_type         = 75,
  drop_money        = 389,
  drop_item         = 50,
  union_number      = 50,
  need_summon_count = 30,
  sell_tab0         = 30,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1350,
  hit_material_type = 7,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 17,
  height            = 0
});
registerNpc(385, {
  walk_speed        = 0,
  run_speed         = 250,
  scale             = 700,
  r_weapon          = 100,
  l_weapon          = 1079,
  level             = 0,
  hp                = 127,
  attack            = 44,
  hit               = 551,
  def               = 294,
  res               = 614,
  avoid             = 489,
  attack_spd        = 197,
  is_magic_damage   = 105,
  ai_type           = 1,
  give_exp          = 146,
  drop_type         = 105,
  drop_money        = 0,
  drop_item         = 57,
  union_number      = 57,
  need_summon_count = 32,
  sell_tab0         = 32,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1400,
  hit_material_type = 7,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 17,
  height            = 0
});
registerNpc(386, {
  walk_speed        = 0,
  run_speed         = 280,
  scale             = 700,
  r_weapon          = 100,
  l_weapon          = 1079,
  level             = 0,
  hp                = 131,
  attack            = 44,
  hit               = 571,
  def               = 304,
  res               = 649,
  avoid             = 508,
  attack_spd        = 204,
  is_magic_damage   = 110,
  ai_type           = 1,
  give_exp          = 146,
  drop_type         = 110,
  drop_money        = 0,
  drop_item         = 65,
  union_number      = 65,
  need_summon_count = 33,
  sell_tab0         = 33,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1500,
  hit_material_type = 7,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 17,
  height            = 0
});
registerNpc(387, {
  walk_speed        = 0,
  run_speed         = 280,
  scale             = 610,
  r_weapon          = 182,
  l_weapon          = 1079,
  level             = 0,
  hp                = 125,
  attack            = 43,
  hit               = 541,
  def               = 289,
  res               = 597,
  avoid             = 480,
  attack_spd        = 194,
  is_magic_damage   = 110,
  ai_type           = 1,
  give_exp          = 272,
  drop_type         = 106,
  drop_money        = 279,
  drop_item         = 20,
  union_number      = 20,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1500,
  hit_material_type = 7,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 18,
  height            = 0
});
registerNpc(388, {
  walk_speed        = 0,
  run_speed         = 280,
  scale             = 610,
  r_weapon          = 190,
  l_weapon          = 1079,
  level             = 0,
  hp                = 135,
  attack            = 45,
  hit               = 590,
  def               = 314,
  res               = 686,
  avoid             = 527,
  attack_spd        = 211,
  is_magic_damage   = 110,
  ai_type           = 1,
  give_exp          = 272,
  drop_type         = 114,
  drop_money        = 279,
  drop_item         = 20,
  union_number      = 20,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1500,
  hit_material_type = 7,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 18,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end