registerNpc(841, {
  walk_speed        = 200,
  run_speed         = 450,
  scale             = 160,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 70,
  hp                = 2303,
  attack            = 250,
  hit               = 215,
  def               = 208,
  res               = 99,
  avoid             = 89,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 158,
  give_exp          = 36,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 80,
  sell_tab0         = 80,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(842, {
  walk_speed        = 207,
  run_speed         = 464,
  scale             = 166,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 71,
  hp                = 2335,
  attack            = 254,
  hit               = 217,
  def               = 211,
  res               = 100,
  avoid             = 90,
  attack_spd        = 102,
  is_magic_damage   = 0,
  ai_type           = 158,
  give_exp          = 40,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 81,
  sell_tab0         = 81,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(843, {
  walk_speed        = 214,
  run_speed         = 478,
  scale             = 172,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 72,
  hp                = 2367,
  attack            = 258,
  hit               = 220,
  def               = 214,
  res               = 102,
  avoid             = 91,
  attack_spd        = 104,
  is_magic_damage   = 0,
  ai_type           = 158,
  give_exp          = 45,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 82,
  sell_tab0         = 82,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(844, {
  walk_speed        = 221,
  run_speed         = 492,
  scale             = 178,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 73,
  hp                = 2400,
  attack            = 262,
  hit               = 222,
  def               = 218,
  res               = 103,
  avoid             = 93,
  attack_spd        = 106,
  is_magic_damage   = 0,
  ai_type           = 158,
  give_exp          = 49,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 83,
  sell_tab0         = 83,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(845, {
  walk_speed        = 228,
  run_speed         = 506,
  scale             = 184,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 74,
  hp                = 2432,
  attack            = 266,
  hit               = 225,
  def               = 222,
  res               = 105,
  avoid             = 94,
  attack_spd        = 108,
  is_magic_damage   = 0,
  ai_type           = 158,
  give_exp          = 53,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 84,
  sell_tab0         = 84,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(846, {
  walk_speed        = 235,
  run_speed         = 520,
  scale             = 190,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 75,
  hp                = 2465,
  attack            = 270,
  hit               = 227,
  def               = 225,
  res               = 106,
  avoid             = 95,
  attack_spd        = 110,
  is_magic_damage   = 0,
  ai_type           = 158,
  give_exp          = 59,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 85,
  sell_tab0         = 85,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(847, {
  walk_speed        = 242,
  run_speed         = 534,
  scale             = 195,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 76,
  hp                = 2498,
  attack            = 274,
  hit               = 229,
  def               = 229,
  res               = 108,
  avoid             = 96,
  attack_spd        = 112,
  is_magic_damage   = 0,
  ai_type           = 158,
  give_exp          = 63,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 86,
  sell_tab0         = 86,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(848, {
  walk_speed        = 249,
  run_speed         = 548,
  scale             = 200,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 77,
  hp                = 2531,
  attack            = 278,
  hit               = 232,
  def               = 232,
  res               = 109,
  avoid             = 98,
  attack_spd        = 114,
  is_magic_damage   = 0,
  ai_type           = 158,
  give_exp          = 68,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 87,
  sell_tab0         = 87,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(849, {
  walk_speed        = 256,
  run_speed         = 562,
  scale             = 205,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 78,
  hp                = 2564,
  attack            = 282,
  hit               = 234,
  def               = 236,
  res               = 111,
  avoid             = 99,
  attack_spd        = 116,
  is_magic_damage   = 0,
  ai_type           = 158,
  give_exp          = 74,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 88,
  sell_tab0         = 88,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(850, {
  walk_speed        = 263,
  run_speed         = 576,
  scale             = 210,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 80,
  hp                = 2631,
  attack            = 290,
  hit               = 239,
  def               = 243,
  res               = 114,
  avoid             = 101,
  attack_spd        = 118,
  is_magic_damage   = 0,
  ai_type           = 158,
  give_exp          = 79,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 89,
  sell_tab0         = 89,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end