registerNpc(841, {
  walk_speed        = 0,
  run_speed         = 200,
  scale             = 450,
  r_weapon          = 160,
  l_weapon          = 0,
  level             = 0,
  hp                = 70,
  attack            = 2303,
  hit               = 250,
  def               = 215,
  res               = 208,
  avoid             = 99,
  attack_spd        = 89,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 158,
  drop_type         = 36,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 80,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(842, {
  walk_speed        = 0,
  run_speed         = 207,
  scale             = 464,
  r_weapon          = 166,
  l_weapon          = 0,
  level             = 0,
  hp                = 71,
  attack            = 2335,
  hit               = 254,
  def               = 217,
  res               = 211,
  avoid             = 100,
  attack_spd        = 90,
  is_magic_damage   = 102,
  ai_type           = 0,
  give_exp          = 158,
  drop_type         = 40,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 81,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(843, {
  walk_speed        = 0,
  run_speed         = 214,
  scale             = 478,
  r_weapon          = 172,
  l_weapon          = 0,
  level             = 0,
  hp                = 72,
  attack            = 2367,
  hit               = 258,
  def               = 220,
  res               = 214,
  avoid             = 102,
  attack_spd        = 91,
  is_magic_damage   = 104,
  ai_type           = 0,
  give_exp          = 158,
  drop_type         = 45,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 82,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(844, {
  walk_speed        = 0,
  run_speed         = 221,
  scale             = 492,
  r_weapon          = 178,
  l_weapon          = 0,
  level             = 0,
  hp                = 73,
  attack            = 2400,
  hit               = 262,
  def               = 222,
  res               = 218,
  avoid             = 103,
  attack_spd        = 93,
  is_magic_damage   = 106,
  ai_type           = 0,
  give_exp          = 158,
  drop_type         = 49,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 83,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(845, {
  walk_speed        = 0,
  run_speed         = 228,
  scale             = 506,
  r_weapon          = 184,
  l_weapon          = 0,
  level             = 0,
  hp                = 74,
  attack            = 2432,
  hit               = 266,
  def               = 225,
  res               = 222,
  avoid             = 105,
  attack_spd        = 94,
  is_magic_damage   = 108,
  ai_type           = 0,
  give_exp          = 158,
  drop_type         = 53,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 84,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(846, {
  walk_speed        = 0,
  run_speed         = 235,
  scale             = 520,
  r_weapon          = 190,
  l_weapon          = 0,
  level             = 0,
  hp                = 75,
  attack            = 2465,
  hit               = 270,
  def               = 227,
  res               = 225,
  avoid             = 106,
  attack_spd        = 95,
  is_magic_damage   = 110,
  ai_type           = 0,
  give_exp          = 158,
  drop_type         = 59,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 85,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(847, {
  walk_speed        = 0,
  run_speed         = 242,
  scale             = 534,
  r_weapon          = 195,
  l_weapon          = 0,
  level             = 0,
  hp                = 76,
  attack            = 2498,
  hit               = 274,
  def               = 229,
  res               = 229,
  avoid             = 108,
  attack_spd        = 96,
  is_magic_damage   = 112,
  ai_type           = 0,
  give_exp          = 158,
  drop_type         = 63,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 86,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(848, {
  walk_speed        = 0,
  run_speed         = 249,
  scale             = 548,
  r_weapon          = 200,
  l_weapon          = 0,
  level             = 0,
  hp                = 77,
  attack            = 2531,
  hit               = 278,
  def               = 232,
  res               = 232,
  avoid             = 109,
  attack_spd        = 98,
  is_magic_damage   = 114,
  ai_type           = 0,
  give_exp          = 158,
  drop_type         = 68,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 87,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(849, {
  walk_speed        = 0,
  run_speed         = 256,
  scale             = 562,
  r_weapon          = 205,
  l_weapon          = 0,
  level             = 0,
  hp                = 78,
  attack            = 2564,
  hit               = 282,
  def               = 234,
  res               = 236,
  avoid             = 111,
  attack_spd        = 99,
  is_magic_damage   = 116,
  ai_type           = 0,
  give_exp          = 158,
  drop_type         = 74,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 88,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(850, {
  walk_speed        = 0,
  run_speed         = 263,
  scale             = 576,
  r_weapon          = 210,
  l_weapon          = 0,
  level             = 0,
  hp                = 80,
  attack            = 2631,
  hit               = 290,
  def               = 239,
  res               = 243,
  avoid             = 114,
  attack_spd        = 101,
  is_magic_damage   = 118,
  ai_type           = 0,
  give_exp          = 158,
  drop_type         = 79,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 89,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end