registerNpc(831, {
  walk_speed        = 0,
  run_speed         = 220,
  scale             = 490,
  r_weapon          = 120,
  l_weapon          = 1095,
  level             = 0,
  hp                = 72,
  attack            = 1919,
  hit               = 237,
  def               = 219,
  res               = 193,
  avoid             = 90,
  attack_spd        = 107,
  is_magic_damage   = 100,
  ai_type           = 1,
  give_exp          = 157,
  drop_type         = 117,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 60,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1200,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(832, {
  walk_speed        = 0,
  run_speed         = 226,
  scale             = 502,
  r_weapon          = 125,
  l_weapon          = 1095,
  level             = 0,
  hp                = 73,
  attack            = 1946,
  hit               = 241,
  def               = 222,
  res               = 196,
  avoid             = 92,
  attack_spd        = 108,
  is_magic_damage   = 102,
  ai_type           = 1,
  give_exp          = 157,
  drop_type         = 124,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 61,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1220,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(833, {
  walk_speed        = 0,
  run_speed         = 232,
  scale             = 514,
  r_weapon          = 130,
  l_weapon          = 1095,
  level             = 0,
  hp                = 74,
  attack            = 1974,
  hit               = 245,
  def               = 224,
  res               = 199,
  avoid             = 93,
  attack_spd        = 110,
  is_magic_damage   = 104,
  ai_type           = 1,
  give_exp          = 157,
  drop_type         = 127,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 62,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1240,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(834, {
  walk_speed        = 0,
  run_speed         = 238,
  scale             = 526,
  r_weapon          = 135,
  l_weapon          = 1095,
  level             = 0,
  hp                = 75,
  attack            = 2002,
  hit               = 249,
  def               = 227,
  res               = 203,
  avoid             = 95,
  attack_spd        = 111,
  is_magic_damage   = 106,
  ai_type           = 1,
  give_exp          = 157,
  drop_type         = 133,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 63,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1260,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(835, {
  walk_speed        = 0,
  run_speed         = 244,
  scale             = 538,
  r_weapon          = 140,
  l_weapon          = 1095,
  level             = 0,
  hp                = 76,
  attack            = 2030,
  hit               = 252,
  def               = 229,
  res               = 206,
  avoid             = 96,
  attack_spd        = 112,
  is_magic_damage   = 108,
  ai_type           = 1,
  give_exp          = 157,
  drop_type         = 143,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 64,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1270,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(836, {
  walk_speed        = 0,
  run_speed         = 250,
  scale             = 550,
  r_weapon          = 144,
  l_weapon          = 1095,
  level             = 0,
  hp                = 77,
  attack            = 2058,
  hit               = 256,
  def               = 232,
  res               = 209,
  avoid             = 97,
  attack_spd        = 114,
  is_magic_damage   = 110,
  ai_type           = 1,
  give_exp          = 157,
  drop_type         = 149,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 65,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1280,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(837, {
  walk_speed        = 0,
  run_speed         = 256,
  scale             = 562,
  r_weapon          = 148,
  l_weapon          = 1095,
  level             = 0,
  hp                = 78,
  attack            = 2086,
  hit               = 260,
  def               = 234,
  res               = 213,
  avoid             = 99,
  attack_spd        = 115,
  is_magic_damage   = 112,
  ai_type           = 1,
  give_exp          = 157,
  drop_type         = 156,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 66,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1290,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(838, {
  walk_speed        = 0,
  run_speed         = 262,
  scale             = 574,
  r_weapon          = 152,
  l_weapon          = 1095,
  level             = 0,
  hp                = 79,
  attack            = 2115,
  hit               = 264,
  def               = 237,
  res               = 216,
  avoid             = 100,
  attack_spd        = 117,
  is_magic_damage   = 114,
  ai_type           = 1,
  give_exp          = 157,
  drop_type         = 164,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 67,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1300,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(839, {
  walk_speed        = 0,
  run_speed         = 268,
  scale             = 586,
  r_weapon          = 156,
  l_weapon          = 1095,
  level             = 0,
  hp                = 80,
  attack            = 2143,
  hit               = 267,
  def               = 239,
  res               = 220,
  avoid             = 102,
  attack_spd        = 118,
  is_magic_damage   = 116,
  ai_type           = 1,
  give_exp          = 157,
  drop_type         = 171,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 68,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1310,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(840, {
  walk_speed        = 0,
  run_speed         = 274,
  scale             = 598,
  r_weapon          = 160,
  l_weapon          = 1095,
  level             = 0,
  hp                = 82,
  attack            = 2201,
  hit               = 275,
  def               = 244,
  res               = 226,
  avoid             = 104,
  attack_spd        = 121,
  is_magic_damage   = 118,
  ai_type           = 1,
  give_exp          = 157,
  drop_type         = 179,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 69,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1320,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end