registerNpc(831, {
  walk_speed        = 220,
  run_speed         = 490,
  scale             = 120,
  r_weapon          = 1095,
  l_weapon          = 0,
  level             = 72,
  hp                = 1919,
  attack            = 237,
  hit               = 219,
  def               = 193,
  res               = 90,
  avoid             = 107,
  attack_spd        = 100,
  is_magic_damage   = 1,
  ai_type           = 157,
  give_exp          = 117,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 60,
  sell_tab0         = 60,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1200,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(832, {
  walk_speed        = 226,
  run_speed         = 502,
  scale             = 125,
  r_weapon          = 1095,
  l_weapon          = 0,
  level             = 73,
  hp                = 1946,
  attack            = 241,
  hit               = 222,
  def               = 196,
  res               = 92,
  avoid             = 108,
  attack_spd        = 102,
  is_magic_damage   = 1,
  ai_type           = 157,
  give_exp          = 124,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 61,
  sell_tab0         = 61,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1220,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(833, {
  walk_speed        = 232,
  run_speed         = 514,
  scale             = 130,
  r_weapon          = 1095,
  l_weapon          = 0,
  level             = 74,
  hp                = 1974,
  attack            = 245,
  hit               = 224,
  def               = 199,
  res               = 93,
  avoid             = 110,
  attack_spd        = 104,
  is_magic_damage   = 1,
  ai_type           = 157,
  give_exp          = 127,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 62,
  sell_tab0         = 62,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1240,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(834, {
  walk_speed        = 238,
  run_speed         = 526,
  scale             = 135,
  r_weapon          = 1095,
  l_weapon          = 0,
  level             = 75,
  hp                = 2002,
  attack            = 249,
  hit               = 227,
  def               = 203,
  res               = 95,
  avoid             = 111,
  attack_spd        = 106,
  is_magic_damage   = 1,
  ai_type           = 157,
  give_exp          = 133,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 63,
  sell_tab0         = 63,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1260,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(835, {
  walk_speed        = 244,
  run_speed         = 538,
  scale             = 140,
  r_weapon          = 1095,
  l_weapon          = 0,
  level             = 76,
  hp                = 2030,
  attack            = 252,
  hit               = 229,
  def               = 206,
  res               = 96,
  avoid             = 112,
  attack_spd        = 108,
  is_magic_damage   = 1,
  ai_type           = 157,
  give_exp          = 143,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 64,
  sell_tab0         = 64,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1270,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(836, {
  walk_speed        = 250,
  run_speed         = 550,
  scale             = 144,
  r_weapon          = 1095,
  l_weapon          = 0,
  level             = 77,
  hp                = 2058,
  attack            = 256,
  hit               = 232,
  def               = 209,
  res               = 97,
  avoid             = 114,
  attack_spd        = 110,
  is_magic_damage   = 1,
  ai_type           = 157,
  give_exp          = 149,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 65,
  sell_tab0         = 65,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1280,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(837, {
  walk_speed        = 256,
  run_speed         = 562,
  scale             = 148,
  r_weapon          = 1095,
  l_weapon          = 0,
  level             = 78,
  hp                = 2086,
  attack            = 260,
  hit               = 234,
  def               = 213,
  res               = 99,
  avoid             = 115,
  attack_spd        = 112,
  is_magic_damage   = 1,
  ai_type           = 157,
  give_exp          = 156,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 66,
  sell_tab0         = 66,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1290,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(838, {
  walk_speed        = 262,
  run_speed         = 574,
  scale             = 152,
  r_weapon          = 1095,
  l_weapon          = 0,
  level             = 79,
  hp                = 2115,
  attack            = 264,
  hit               = 237,
  def               = 216,
  res               = 100,
  avoid             = 117,
  attack_spd        = 114,
  is_magic_damage   = 1,
  ai_type           = 157,
  give_exp          = 164,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 67,
  sell_tab0         = 67,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1300,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(839, {
  walk_speed        = 268,
  run_speed         = 586,
  scale             = 156,
  r_weapon          = 1095,
  l_weapon          = 0,
  level             = 80,
  hp                = 2143,
  attack            = 267,
  hit               = 239,
  def               = 220,
  res               = 102,
  avoid             = 118,
  attack_spd        = 116,
  is_magic_damage   = 1,
  ai_type           = 157,
  give_exp          = 171,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 68,
  sell_tab0         = 68,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1310,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(840, {
  walk_speed        = 274,
  run_speed         = 598,
  scale             = 160,
  r_weapon          = 1095,
  l_weapon          = 0,
  level             = 82,
  hp                = 2201,
  attack            = 275,
  hit               = 244,
  def               = 226,
  res               = 104,
  avoid             = 121,
  attack_spd        = 118,
  is_magic_damage   = 1,
  ai_type           = 157,
  give_exp          = 179,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 69,
  sell_tab0         = 69,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1320,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end