registerNpc(701, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 250,
  r_weapon          = 110,
  l_weapon          = 0,
  level             = 0,
  hp                = 1,
  attack            = 73,
  hit               = 1,
  def               = 1,
  res               = 200,
  avoid             = 200,
  attack_spd        = 300,
  is_magic_damage   = 110,
  ai_type           = 0,
  give_exp          = 31,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(702, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 250,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 40,
  attack            = 19,
  hit               = 1,
  def               = 1,
  res               = 200,
  avoid             = 200,
  attack_spd        = 300,
  is_magic_damage   = 108,
  ai_type           = 0,
  give_exp          = 32,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(704, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 250,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 90,
  attack            = 23,
  hit               = 1,
  def               = 1,
  res               = 200,
  avoid             = 200,
  attack_spd        = 300,
  is_magic_damage   = 104,
  ai_type           = 0,
  give_exp          = 34,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(705, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 250,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 90,
  attack            = 23,
  hit               = 1,
  def               = 1,
  res               = 200,
  avoid             = 200,
  attack_spd        = 300,
  is_magic_damage   = 102,
  ai_type           = 0,
  give_exp          = 35,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(706, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 250,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 90,
  attack            = 23,
  hit               = 1,
  def               = 1,
  res               = 200,
  avoid             = 200,
  attack_spd        = 300,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 31,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(707, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 250,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 90,
  attack            = 23,
  hit               = 1,
  def               = 1,
  res               = 200,
  avoid             = 200,
  attack_spd        = 300,
  is_magic_damage   = 98,
  ai_type           = 0,
  give_exp          = 31,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(708, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 250,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 90,
  attack            = 23,
  hit               = 1,
  def               = 1,
  res               = 200,
  avoid             = 200,
  attack_spd        = 300,
  is_magic_damage   = 96,
  ai_type           = 0,
  give_exp          = 31,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(709, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 250,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 90,
  attack            = 23,
  hit               = 1,
  def               = 1,
  res               = 200,
  avoid             = 200,
  attack_spd        = 300,
  is_magic_damage   = 94,
  ai_type           = 0,
  give_exp          = 31,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(710, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 250,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 90,
  attack            = 23,
  hit               = 1,
  def               = 1,
  res               = 200,
  avoid             = 200,
  attack_spd        = 300,
  is_magic_damage   = 92,
  ai_type           = 0,
  give_exp          = 31,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end