registerNpc(701, {
  walk_speed        = 160,
  run_speed         = 250,
  scale             = 110,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 1,
  hp                = 73,
  attack            = 1,
  hit               = 1,
  def               = 200,
  res               = 200,
  avoid             = 300,
  attack_spd        = 110,
  is_magic_damage   = 0,
  ai_type           = 31,
  give_exp          = 0,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(702, {
  walk_speed        = 160,
  run_speed         = 250,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 40,
  hp                = 19,
  attack            = 1,
  hit               = 1,
  def               = 200,
  res               = 200,
  avoid             = 300,
  attack_spd        = 108,
  is_magic_damage   = 0,
  ai_type           = 32,
  give_exp          = 0,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(704, {
  walk_speed        = 160,
  run_speed         = 250,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 90,
  hp                = 23,
  attack            = 1,
  hit               = 1,
  def               = 200,
  res               = 200,
  avoid             = 300,
  attack_spd        = 104,
  is_magic_damage   = 0,
  ai_type           = 34,
  give_exp          = 0,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(705, {
  walk_speed        = 160,
  run_speed         = 250,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 90,
  hp                = 23,
  attack            = 1,
  hit               = 1,
  def               = 200,
  res               = 200,
  avoid             = 300,
  attack_spd        = 102,
  is_magic_damage   = 0,
  ai_type           = 35,
  give_exp          = 0,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(706, {
  walk_speed        = 160,
  run_speed         = 250,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 90,
  hp                = 23,
  attack            = 1,
  hit               = 1,
  def               = 200,
  res               = 200,
  avoid             = 300,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 31,
  give_exp          = 0,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(707, {
  walk_speed        = 160,
  run_speed         = 250,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 90,
  hp                = 23,
  attack            = 1,
  hit               = 1,
  def               = 200,
  res               = 200,
  avoid             = 300,
  attack_spd        = 98,
  is_magic_damage   = 0,
  ai_type           = 31,
  give_exp          = 0,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(708, {
  walk_speed        = 160,
  run_speed         = 250,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 90,
  hp                = 23,
  attack            = 1,
  hit               = 1,
  def               = 200,
  res               = 200,
  avoid             = 300,
  attack_spd        = 96,
  is_magic_damage   = 0,
  ai_type           = 31,
  give_exp          = 0,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(709, {
  walk_speed        = 160,
  run_speed         = 250,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 90,
  hp                = 23,
  attack            = 1,
  hit               = 1,
  def               = 200,
  res               = 200,
  avoid             = 300,
  attack_spd        = 94,
  is_magic_damage   = 0,
  ai_type           = 31,
  give_exp          = 0,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(710, {
  walk_speed        = 160,
  run_speed         = 250,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 90,
  hp                = 23,
  attack            = 1,
  hit               = 1,
  def               = 200,
  res               = 200,
  avoid             = 300,
  attack_spd        = 92,
  is_magic_damage   = 0,
  ai_type           = 31,
  give_exp          = 0,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end