registerNpc(881, {
  walk_speed        = 360,
  run_speed         = 770,
  scale             = 86,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 72,
  hp                = 1379,
  attack            = 244,
  hit               = 247,
  def               = 182,
  res               = 123,
  avoid             = 174,
  attack_spd        = 110,
  is_magic_damage   = 0,
  ai_type           = 162,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 26,
  sell_tab0         = 26,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 180,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(882, {
  walk_speed        = 368,
  run_speed         = 786,
  scale             = 90,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 73,
  hp                = 1399,
  attack            = 247,
  hit               = 250,
  def               = 186,
  res               = 125,
  avoid             = 176,
  attack_spd        = 112,
  is_magic_damage   = 0,
  ai_type           = 162,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 26,
  sell_tab0         = 26,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 180,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(883, {
  walk_speed        = 376,
  run_speed         = 802,
  scale             = 94,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 74,
  hp                = 1420,
  attack            = 251,
  hit               = 252,
  def               = 189,
  res               = 127,
  avoid             = 179,
  attack_spd        = 114,
  is_magic_damage   = 0,
  ai_type           = 162,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 26,
  sell_tab0         = 26,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 180,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(884, {
  walk_speed        = 384,
  run_speed         = 818,
  scale             = 98,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 75,
  hp                = 1440,
  attack            = 255,
  hit               = 255,
  def               = 192,
  res               = 129,
  avoid             = 182,
  attack_spd        = 116,
  is_magic_damage   = 0,
  ai_type           = 162,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 26,
  sell_tab0         = 26,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 180,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(885, {
  walk_speed        = 392,
  run_speed         = 834,
  scale             = 102,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 76,
  hp                = 1461,
  attack            = 259,
  hit               = 258,
  def               = 195,
  res               = 131,
  avoid             = 185,
  attack_spd        = 118,
  is_magic_damage   = 0,
  ai_type           = 162,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 26,
  sell_tab0         = 26,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 180,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(886, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 106,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 77,
  hp                = 1482,
  attack            = 263,
  hit               = 261,
  def               = 198,
  res               = 133,
  avoid             = 188,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 162,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 26,
  sell_tab0         = 26,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 180,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(887, {
  walk_speed        = 408,
  run_speed         = 866,
  scale             = 110,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 78,
  hp                = 1502,
  attack            = 267,
  hit               = 263,
  def               = 201,
  res               = 134,
  avoid             = 191,
  attack_spd        = 122,
  is_magic_damage   = 0,
  ai_type           = 162,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 26,
  sell_tab0         = 26,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 180,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(888, {
  walk_speed        = 416,
  run_speed         = 882,
  scale             = 114,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 79,
  hp                = 1523,
  attack            = 270,
  hit               = 266,
  def               = 205,
  res               = 136,
  avoid             = 194,
  attack_spd        = 124,
  is_magic_damage   = 0,
  ai_type           = 162,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 26,
  sell_tab0         = 26,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 180,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(889, {
  walk_speed        = 424,
  run_speed         = 898,
  scale             = 118,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 80,
  hp                = 1544,
  attack            = 274,
  hit               = 269,
  def               = 208,
  res               = 138,
  avoid             = 197,
  attack_spd        = 126,
  is_magic_damage   = 0,
  ai_type           = 162,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 26,
  sell_tab0         = 26,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 180,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(890, {
  walk_speed        = 432,
  run_speed         = 914,
  scale             = 122,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 82,
  hp                = 1587,
  attack            = 282,
  hit               = 274,
  def               = 214,
  res               = 142,
  avoid             = 203,
  attack_spd        = 128,
  is_magic_damage   = 0,
  ai_type           = 162,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 26,
  sell_tab0         = 26,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 180,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end