registerNpc(881, {
  walk_speed        = 0,
  run_speed         = 360,
  scale             = 770,
  r_weapon          = 86,
  l_weapon          = 0,
  level             = 0,
  hp                = 72,
  attack            = 1379,
  hit               = 244,
  def               = 247,
  res               = 182,
  avoid             = 123,
  attack_spd        = 174,
  is_magic_damage   = 110,
  ai_type           = 0,
  give_exp          = 162,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 26,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 180,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(882, {
  walk_speed        = 0,
  run_speed         = 368,
  scale             = 786,
  r_weapon          = 90,
  l_weapon          = 0,
  level             = 0,
  hp                = 73,
  attack            = 1399,
  hit               = 247,
  def               = 250,
  res               = 186,
  avoid             = 125,
  attack_spd        = 176,
  is_magic_damage   = 112,
  ai_type           = 0,
  give_exp          = 162,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 26,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 180,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(883, {
  walk_speed        = 0,
  run_speed         = 376,
  scale             = 802,
  r_weapon          = 94,
  l_weapon          = 0,
  level             = 0,
  hp                = 74,
  attack            = 1420,
  hit               = 251,
  def               = 252,
  res               = 189,
  avoid             = 127,
  attack_spd        = 179,
  is_magic_damage   = 114,
  ai_type           = 0,
  give_exp          = 162,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 26,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 180,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(884, {
  walk_speed        = 0,
  run_speed         = 384,
  scale             = 818,
  r_weapon          = 98,
  l_weapon          = 0,
  level             = 0,
  hp                = 75,
  attack            = 1440,
  hit               = 255,
  def               = 255,
  res               = 192,
  avoid             = 129,
  attack_spd        = 182,
  is_magic_damage   = 116,
  ai_type           = 0,
  give_exp          = 162,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 26,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 180,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(885, {
  walk_speed        = 0,
  run_speed         = 392,
  scale             = 834,
  r_weapon          = 102,
  l_weapon          = 0,
  level             = 0,
  hp                = 76,
  attack            = 1461,
  hit               = 259,
  def               = 258,
  res               = 195,
  avoid             = 131,
  attack_spd        = 185,
  is_magic_damage   = 118,
  ai_type           = 0,
  give_exp          = 162,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 26,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 180,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(886, {
  walk_speed        = 0,
  run_speed         = 400,
  scale             = 850,
  r_weapon          = 106,
  l_weapon          = 0,
  level             = 0,
  hp                = 77,
  attack            = 1482,
  hit               = 263,
  def               = 261,
  res               = 198,
  avoid             = 133,
  attack_spd        = 188,
  is_magic_damage   = 120,
  ai_type           = 0,
  give_exp          = 162,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 26,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 180,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(887, {
  walk_speed        = 0,
  run_speed         = 408,
  scale             = 866,
  r_weapon          = 110,
  l_weapon          = 0,
  level             = 0,
  hp                = 78,
  attack            = 1502,
  hit               = 267,
  def               = 263,
  res               = 201,
  avoid             = 134,
  attack_spd        = 191,
  is_magic_damage   = 122,
  ai_type           = 0,
  give_exp          = 162,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 26,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 180,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(888, {
  walk_speed        = 0,
  run_speed         = 416,
  scale             = 882,
  r_weapon          = 114,
  l_weapon          = 0,
  level             = 0,
  hp                = 79,
  attack            = 1523,
  hit               = 270,
  def               = 266,
  res               = 205,
  avoid             = 136,
  attack_spd        = 194,
  is_magic_damage   = 124,
  ai_type           = 0,
  give_exp          = 162,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 26,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 180,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(889, {
  walk_speed        = 0,
  run_speed         = 424,
  scale             = 898,
  r_weapon          = 118,
  l_weapon          = 0,
  level             = 0,
  hp                = 80,
  attack            = 1544,
  hit               = 274,
  def               = 269,
  res               = 208,
  avoid             = 138,
  attack_spd        = 197,
  is_magic_damage   = 126,
  ai_type           = 0,
  give_exp          = 162,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 26,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 180,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(890, {
  walk_speed        = 0,
  run_speed         = 432,
  scale             = 914,
  r_weapon          = 122,
  l_weapon          = 0,
  level             = 0,
  hp                = 82,
  attack            = 1587,
  hit               = 282,
  def               = 274,
  res               = 214,
  avoid             = 142,
  attack_spd        = 203,
  is_magic_damage   = 128,
  ai_type           = 0,
  give_exp          = 162,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 26,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 180,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end