registerNpc(64, {
  walk_speed        = 260,
  run_speed         = 600,
  scale             = 80,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 18,
  hp                = 25,
  attack            = 93,
  hit               = 92,
  def               = 65,
  res               = 22,
  avoid             = 21,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 9,
  give_exp          = 29,
  drop_type         = 127,
  drop_money        = 12,
  drop_item         = 65,
  union_number      = 65,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 4,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(506, {
  walk_speed        = 350,
  run_speed         = 750,
  scale             = 50,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 135,
  hp                = 7,
  attack            = 434,
  hit               = 586,
  def               = 235,
  res               = 473,
  avoid             = 172,
  attack_spd        = 90,
  is_magic_damage   = 0,
  ai_type           = 302,
  give_exp          = 1,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 240,
  npc_type          = 4,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(507, {
  walk_speed        = 350,
  run_speed         = 750,
  scale             = 50,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 148,
  hp                = 10,
  attack            = 487,
  hit               = 643,
  def               = 265,
  res               = 535,
  avoid             = 191,
  attack_spd        = 90,
  is_magic_damage   = 0,
  ai_type           = 302,
  give_exp          = 1,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 240,
  npc_type          = 4,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(508, {
  walk_speed        = 350,
  run_speed         = 750,
  scale             = 50,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 160,
  hp                = 12,
  attack            = 537,
  hit               = 697,
  def               = 294,
  res               = 594,
  avoid             = 210,
  attack_spd        = 90,
  is_magic_damage   = 0,
  ai_type           = 302,
  give_exp          = 1,
  drop_type         = 0,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 240,
  npc_type          = 4,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(907, {
  walk_speed        = 260,
  run_speed         = 360,
  scale             = 88,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 38,
  hp                = 1308,
  attack            = 128,
  hit               = 119,
  def               = 113,
  res               = 41,
  avoid             = 45,
  attack_spd        = 80,
  is_magic_damage   = 0,
  ai_type           = 166,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 29,
  sell_tab0         = 29,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end