registerNpc(64, {
  walk_speed        = 0,
  run_speed         = 260,
  scale             = 600,
  r_weapon          = 80,
  l_weapon          = 0,
  level             = 0,
  hp                = 18,
  attack            = 25,
  hit               = 93,
  def               = 92,
  res               = 65,
  avoid             = 22,
  attack_spd        = 21,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 9,
  drop_type         = 29,
  drop_money        = 127,
  drop_item         = 12,
  union_number      = 12,
  need_summon_count = 65,
  sell_tab0         = 65,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 4,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 11,
  height            = 0
});
registerNpc(506, {
  walk_speed        = 0,
  run_speed         = 350,
  scale             = 750,
  r_weapon          = 50,
  l_weapon          = 0,
  level             = 0,
  hp                = 135,
  attack            = 7,
  hit               = 434,
  def               = 586,
  res               = 235,
  avoid             = 473,
  attack_spd        = 172,
  is_magic_damage   = 90,
  ai_type           = 0,
  give_exp          = 302,
  drop_type         = 1,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 240,
  hit_material_type = 4,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 20,
  height            = 0
});
registerNpc(507, {
  walk_speed        = 0,
  run_speed         = 350,
  scale             = 750,
  r_weapon          = 50,
  l_weapon          = 0,
  level             = 0,
  hp                = 148,
  attack            = 10,
  hit               = 487,
  def               = 643,
  res               = 265,
  avoid             = 535,
  attack_spd        = 191,
  is_magic_damage   = 90,
  ai_type           = 0,
  give_exp          = 302,
  drop_type         = 1,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 240,
  hit_material_type = 4,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 20,
  height            = 0
});
registerNpc(508, {
  walk_speed        = 0,
  run_speed         = 350,
  scale             = 750,
  r_weapon          = 50,
  l_weapon          = 0,
  level             = 0,
  hp                = 160,
  attack            = 12,
  hit               = 537,
  def               = 697,
  res               = 294,
  avoid             = 594,
  attack_spd        = 210,
  is_magic_damage   = 90,
  ai_type           = 0,
  give_exp          = 302,
  drop_type         = 1,
  drop_money        = 0,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 240,
  hit_material_type = 4,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 21,
  height            = 0
});
registerNpc(907, {
  walk_speed        = 0,
  run_speed         = 260,
  scale             = 360,
  r_weapon          = 88,
  l_weapon          = 0,
  level             = 0,
  hp                = 38,
  attack            = 1308,
  hit               = 128,
  def               = 119,
  res               = 113,
  avoid             = 41,
  attack_spd        = 45,
  is_magic_damage   = 80,
  ai_type           = 0,
  give_exp          = 166,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 29,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end