registerNpc(410, {
  walk_speed        = 300,
  run_speed         = 720,
  scale             = 400,
  r_weapon          = 175,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 780,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(412, {
  walk_speed        = 400,
  run_speed         = 1000,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(413, {
  walk_speed        = 400,
  run_speed         = 1000,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(414, {
  walk_speed        = 400,
  run_speed         = 1000,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(415, {
  walk_speed        = 400,
  run_speed         = 750,
  scale             = 350,
  r_weapon          = 1003,
  l_weapon          = 302,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(416, {
  walk_speed        = 400,
  run_speed         = 800,
  scale             = 350,
  r_weapon          = 135,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(417, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 350,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(418, {
  walk_speed        = 400,
  run_speed         = 1000,
  scale             = 250,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(419, {
  walk_speed        = 400,
  run_speed         = 1000,
  scale             = 300,
  r_weapon          = 1032,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(420, {
  walk_speed        = 400,
  run_speed         = 1000,
  scale             = 300,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(421, {
  walk_speed        = 450,
  run_speed         = 1000,
  scale             = 350,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(422, {
  walk_speed        = 450,
  run_speed         = 1000,
  scale             = 400,
  r_weapon          = 1116,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(423, {
  walk_speed        = 450,
  run_speed         = 1000,
  scale             = 450,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 110,
  hp                = 290,
  attack            = 661,
  hit               = 394,
  def               = 0,
  res               = 302,
  avoid             = 211,
  attack_spd        = 120,
  is_magic_damage   = 0,
  ai_type           = 78,
  give_exp          = 2491,
  drop_type         = 310,
  drop_money        = 1,
  drop_item         = 97,
  union_number      = 97,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end