registerNpc(851, {
  walk_speed        = 225,
  run_speed         = 500,
  scale             = 102,
  r_weapon          = 8,
  l_weapon          = 0,
  level             = 20,
  hp                = 620,
  attack            = 1,
  hit               = 1,
  def               = 10,
  res               = 5,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 159,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 280,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(852, {
  walk_speed        = 231,
  run_speed         = 512,
  scale             = 107,
  r_weapon          = 9,
  l_weapon          = 0,
  level             = 30,
  hp                = 840,
  attack            = 1,
  hit               = 1,
  def               = 12,
  res               = 6,
  avoid             = 1,
  attack_spd        = 102,
  is_magic_damage   = 0,
  ai_type           = 159,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 280,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(853, {
  walk_speed        = 237,
  run_speed         = 524,
  scale             = 112,
  r_weapon          = 107,
  l_weapon          = 0,
  level             = 40,
  hp                = 1000,
  attack            = 1,
  hit               = 1,
  def               = 14,
  res               = 7,
  avoid             = 1,
  attack_spd        = 104,
  is_magic_damage   = 0,
  ai_type           = 159,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 280,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(854, {
  walk_speed        = 243,
  run_speed         = 536,
  scale             = 117,
  r_weapon          = 108,
  l_weapon          = 0,
  level             = 50,
  hp                = 1100,
  attack            = 1,
  hit               = 1,
  def               = 16,
  res               = 8,
  avoid             = 1,
  attack_spd        = 106,
  is_magic_damage   = 0,
  ai_type           = 159,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 280,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(855, {
  walk_speed        = 249,
  run_speed         = 548,
  scale             = 122,
  r_weapon          = 10,
  l_weapon          = 0,
  level             = 60,
  hp                = 1200,
  attack            = 1,
  hit               = 1,
  def               = 18,
  res               = 9,
  avoid             = 1,
  attack_spd        = 108,
  is_magic_damage   = 0,
  ai_type           = 159,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 280,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(856, {
  walk_speed        = 255,
  run_speed         = 560,
  scale             = 126,
  r_weapon          = 109,
  l_weapon          = 0,
  level             = 60,
  hp                = 1940,
  attack            = 191,
  hit               = 169,
  def               = 194,
  res               = 101,
  avoid             = 68,
  attack_spd        = 110,
  is_magic_damage   = 0,
  ai_type           = 159,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 280,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(857, {
  walk_speed        = 261,
  run_speed         = 572,
  scale             = 130,
  r_weapon          = 11,
  l_weapon          = 0,
  level             = 61,
  hp                = 1971,
  attack            = 195,
  hit               = 171,
  def               = 198,
  res               = 103,
  avoid             = 69,
  attack_spd        = 112,
  is_magic_damage   = 0,
  ai_type           = 159,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 280,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(858, {
  walk_speed        = 267,
  run_speed         = 584,
  scale             = 134,
  r_weapon          = 110,
  l_weapon          = 0,
  level             = 62,
  hp                = 2002,
  attack            = 198,
  hit               = 173,
  def               = 203,
  res               = 104,
  avoid             = 70,
  attack_spd        = 114,
  is_magic_damage   = 0,
  ai_type           = 159,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 280,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(859, {
  walk_speed        = 273,
  run_speed         = 596,
  scale             = 138,
  r_weapon          = 111,
  l_weapon          = 0,
  level             = 63,
  hp                = 2033,
  attack            = 202,
  hit               = 175,
  def               = 207,
  res               = 106,
  avoid             = 71,
  attack_spd        = 116,
  is_magic_damage   = 0,
  ai_type           = 159,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 280,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(860, {
  walk_speed        = 279,
  run_speed         = 608,
  scale             = 142,
  r_weapon          = 112,
  l_weapon          = 0,
  level             = 65,
  hp                = 2095,
  attack            = 209,
  hit               = 180,
  def               = 216,
  res               = 109,
  avoid             = 73,
  attack_spd        = 118,
  is_magic_damage   = 0,
  ai_type           = 159,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 280,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end