registerNpc(861, {
  walk_speed        = 230,
  run_speed         = 510,
  scale             = 104,
  r_weapon          = 203,
  l_weapon          = 0,
  level             = 80,
  hp                = 80,
  attack            = 71,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 160,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1550,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(862, {
  walk_speed        = 235,
  run_speed         = 520,
  scale             = 109,
  r_weapon          = 203,
  l_weapon          = 0,
  level             = 90,
  hp                = 90,
  attack            = 86,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 102,
  is_magic_damage   = 0,
  ai_type           = 160,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1600,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(863, {
  walk_speed        = 240,
  run_speed         = 530,
  scale             = 114,
  r_weapon          = 204,
  l_weapon          = 0,
  level             = 100,
  hp                = 100,
  attack            = 104,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 104,
  is_magic_damage   = 0,
  ai_type           = 160,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1650,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(864, {
  walk_speed        = 245,
  run_speed         = 540,
  scale             = 119,
  r_weapon          = 204,
  l_weapon          = 0,
  level             = 110,
  hp                = 110,
  attack            = 125,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 106,
  is_magic_damage   = 0,
  ai_type           = 160,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1700,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(865, {
  walk_speed        = 250,
  run_speed         = 550,
  scale             = 124,
  r_weapon          = 205,
  l_weapon          = 0,
  level             = 120,
  hp                = 120,
  attack            = 148,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 108,
  is_magic_damage   = 0,
  ai_type           = 160,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1750,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(866, {
  walk_speed        = 255,
  run_speed         = 560,
  scale             = 128,
  r_weapon          = 205,
  l_weapon          = 0,
  level             = 69,
  hp                = 1889,
  attack            = 226,
  hit               = 212,
  def               = 183,
  res               = 86,
  avoid             = 102,
  attack_spd        = 110,
  is_magic_damage   = 0,
  ai_type           = 160,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1800,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(867, {
  walk_speed        = 260,
  run_speed         = 570,
  scale             = 132,
  r_weapon          = 206,
  l_weapon          = 0,
  level             = 70,
  hp                = 1917,
  attack            = 230,
  hit               = 214,
  def               = 186,
  res               = 88,
  avoid             = 104,
  attack_spd        = 112,
  is_magic_damage   = 0,
  ai_type           = 160,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1850,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(868, {
  walk_speed        = 265,
  run_speed         = 580,
  scale             = 136,
  r_weapon          = 207,
  l_weapon          = 0,
  level             = 71,
  hp                = 1945,
  attack            = 234,
  hit               = 217,
  def               = 190,
  res               = 89,
  avoid             = 105,
  attack_spd        = 114,
  is_magic_damage   = 0,
  ai_type           = 160,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1900,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(869, {
  walk_speed        = 270,
  run_speed         = 590,
  scale             = 140,
  r_weapon          = 207,
  l_weapon          = 0,
  level             = 72,
  hp                = 1973,
  attack            = 237,
  hit               = 219,
  def               = 193,
  res               = 90,
  avoid             = 107,
  attack_spd        = 116,
  is_magic_damage   = 0,
  ai_type           = 160,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 1950,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(870, {
  walk_speed        = 275,
  run_speed         = 600,
  scale             = 144,
  r_weapon          = 208,
  l_weapon          = 0,
  level             = 74,
  hp                = 2030,
  attack            = 245,
  hit               = 224,
  def               = 199,
  res               = 93,
  avoid             = 110,
  attack_spd        = 118,
  is_magic_damage   = 0,
  ai_type           = 160,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 2000,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end