registerNpc(851, {
  walk_speed        = 0,
  run_speed         = 225,
  scale             = 500,
  r_weapon          = 102,
  l_weapon          = 8,
  level             = 0,
  hp                = 20,
  attack            = 620,
  hit               = 1,
  def               = 1,
  res               = 10,
  avoid             = 5,
  attack_spd        = 1,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 159,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 45,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 280,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});
registerNpc(852, {
  walk_speed        = 0,
  run_speed         = 231,
  scale             = 512,
  r_weapon          = 107,
  l_weapon          = 9,
  level             = 0,
  hp                = 30,
  attack            = 840,
  hit               = 1,
  def               = 1,
  res               = 12,
  avoid             = 6,
  attack_spd        = 1,
  is_magic_damage   = 102,
  ai_type           = 0,
  give_exp          = 159,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 45,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 280,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});
registerNpc(853, {
  walk_speed        = 0,
  run_speed         = 237,
  scale             = 524,
  r_weapon          = 112,
  l_weapon          = 107,
  level             = 0,
  hp                = 40,
  attack            = 1000,
  hit               = 1,
  def               = 1,
  res               = 14,
  avoid             = 7,
  attack_spd        = 1,
  is_magic_damage   = 104,
  ai_type           = 0,
  give_exp          = 159,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 45,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 280,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});
registerNpc(854, {
  walk_speed        = 0,
  run_speed         = 243,
  scale             = 536,
  r_weapon          = 117,
  l_weapon          = 108,
  level             = 0,
  hp                = 50,
  attack            = 1100,
  hit               = 1,
  def               = 1,
  res               = 16,
  avoid             = 8,
  attack_spd        = 1,
  is_magic_damage   = 106,
  ai_type           = 0,
  give_exp          = 159,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 45,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 280,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});
registerNpc(855, {
  walk_speed        = 0,
  run_speed         = 249,
  scale             = 548,
  r_weapon          = 122,
  l_weapon          = 10,
  level             = 0,
  hp                = 60,
  attack            = 1200,
  hit               = 1,
  def               = 1,
  res               = 18,
  avoid             = 9,
  attack_spd        = 1,
  is_magic_damage   = 108,
  ai_type           = 0,
  give_exp          = 159,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 45,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 280,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});
registerNpc(856, {
  walk_speed        = 0,
  run_speed         = 255,
  scale             = 560,
  r_weapon          = 126,
  l_weapon          = 109,
  level             = 0,
  hp                = 60,
  attack            = 1940,
  hit               = 191,
  def               = 169,
  res               = 194,
  avoid             = 101,
  attack_spd        = 68,
  is_magic_damage   = 110,
  ai_type           = 0,
  give_exp          = 159,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 45,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 280,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});
registerNpc(857, {
  walk_speed        = 0,
  run_speed         = 261,
  scale             = 572,
  r_weapon          = 130,
  l_weapon          = 11,
  level             = 0,
  hp                = 61,
  attack            = 1971,
  hit               = 195,
  def               = 171,
  res               = 198,
  avoid             = 103,
  attack_spd        = 69,
  is_magic_damage   = 112,
  ai_type           = 0,
  give_exp          = 159,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 45,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 280,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});
registerNpc(858, {
  walk_speed        = 0,
  run_speed         = 267,
  scale             = 584,
  r_weapon          = 134,
  l_weapon          = 110,
  level             = 0,
  hp                = 62,
  attack            = 2002,
  hit               = 198,
  def               = 173,
  res               = 203,
  avoid             = 104,
  attack_spd        = 70,
  is_magic_damage   = 114,
  ai_type           = 0,
  give_exp          = 159,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 45,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 280,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});
registerNpc(859, {
  walk_speed        = 0,
  run_speed         = 273,
  scale             = 596,
  r_weapon          = 138,
  l_weapon          = 111,
  level             = 0,
  hp                = 63,
  attack            = 2033,
  hit               = 202,
  def               = 175,
  res               = 207,
  avoid             = 106,
  attack_spd        = 71,
  is_magic_damage   = 116,
  ai_type           = 0,
  give_exp          = 159,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 45,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 280,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});
registerNpc(860, {
  walk_speed        = 0,
  run_speed         = 279,
  scale             = 608,
  r_weapon          = 142,
  l_weapon          = 112,
  level             = 0,
  hp                = 65,
  attack            = 2095,
  hit               = 209,
  def               = 180,
  res               = 216,
  avoid             = 109,
  attack_spd        = 73,
  is_magic_damage   = 118,
  ai_type           = 0,
  give_exp          = 159,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 45,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 280,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end