registerNpc(861, {
  walk_speed        = 0,
  run_speed         = 230,
  scale             = 510,
  r_weapon          = 104,
  l_weapon          = 203,
  level             = 0,
  hp                = 80,
  attack            = 80,
  hit               = 71,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 1,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 160,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1550,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(862, {
  walk_speed        = 0,
  run_speed         = 235,
  scale             = 520,
  r_weapon          = 109,
  l_weapon          = 203,
  level             = 0,
  hp                = 90,
  attack            = 90,
  hit               = 86,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 1,
  is_magic_damage   = 102,
  ai_type           = 0,
  give_exp          = 160,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1600,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(863, {
  walk_speed        = 0,
  run_speed         = 240,
  scale             = 530,
  r_weapon          = 114,
  l_weapon          = 204,
  level             = 0,
  hp                = 100,
  attack            = 100,
  hit               = 104,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 1,
  is_magic_damage   = 104,
  ai_type           = 0,
  give_exp          = 160,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1650,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(864, {
  walk_speed        = 0,
  run_speed         = 245,
  scale             = 540,
  r_weapon          = 119,
  l_weapon          = 204,
  level             = 0,
  hp                = 110,
  attack            = 110,
  hit               = 125,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 1,
  is_magic_damage   = 106,
  ai_type           = 0,
  give_exp          = 160,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1700,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(865, {
  walk_speed        = 0,
  run_speed         = 250,
  scale             = 550,
  r_weapon          = 124,
  l_weapon          = 205,
  level             = 0,
  hp                = 120,
  attack            = 120,
  hit               = 148,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 1,
  is_magic_damage   = 108,
  ai_type           = 0,
  give_exp          = 160,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1750,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(866, {
  walk_speed        = 0,
  run_speed         = 255,
  scale             = 560,
  r_weapon          = 128,
  l_weapon          = 205,
  level             = 0,
  hp                = 69,
  attack            = 1889,
  hit               = 226,
  def               = 212,
  res               = 183,
  avoid             = 86,
  attack_spd        = 102,
  is_magic_damage   = 110,
  ai_type           = 0,
  give_exp          = 160,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1800,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(867, {
  walk_speed        = 0,
  run_speed         = 260,
  scale             = 570,
  r_weapon          = 132,
  l_weapon          = 206,
  level             = 0,
  hp                = 70,
  attack            = 1917,
  hit               = 230,
  def               = 214,
  res               = 186,
  avoid             = 88,
  attack_spd        = 104,
  is_magic_damage   = 112,
  ai_type           = 0,
  give_exp          = 160,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1850,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(868, {
  walk_speed        = 0,
  run_speed         = 265,
  scale             = 580,
  r_weapon          = 136,
  l_weapon          = 207,
  level             = 0,
  hp                = 71,
  attack            = 1945,
  hit               = 234,
  def               = 217,
  res               = 190,
  avoid             = 89,
  attack_spd        = 105,
  is_magic_damage   = 114,
  ai_type           = 0,
  give_exp          = 160,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1900,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(869, {
  walk_speed        = 0,
  run_speed         = 270,
  scale             = 590,
  r_weapon          = 140,
  l_weapon          = 207,
  level             = 0,
  hp                = 72,
  attack            = 1973,
  hit               = 237,
  def               = 219,
  res               = 193,
  avoid             = 90,
  attack_spd        = 107,
  is_magic_damage   = 116,
  ai_type           = 0,
  give_exp          = 160,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 1950,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(870, {
  walk_speed        = 0,
  run_speed         = 275,
  scale             = 600,
  r_weapon          = 144,
  l_weapon          = 208,
  level             = 0,
  hp                = 74,
  attack            = 2030,
  hit               = 245,
  def               = 224,
  res               = 199,
  avoid             = 93,
  attack_spd        = 110,
  is_magic_damage   = 118,
  ai_type           = 0,
  give_exp          = 160,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 2000,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end