registerNpc(821, {
  walk_speed        = 0,
  run_speed         = 140,
  scale             = 700,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 54,
  attack            = 1542,
  hit               = 190,
  def               = 166,
  res               = 141,
  avoid             = 58,
  attack_spd        = 62,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 156,
  drop_type         = 71,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 40,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(822, {
  walk_speed        = 0,
  run_speed         = 144,
  scale             = 710,
  r_weapon          = 135,
  l_weapon          = 0,
  level             = 0,
  hp                = 55,
  attack            = 1569,
  hit               = 194,
  def               = 169,
  res               = 144,
  avoid             = 59,
  attack_spd        = 63,
  is_magic_damage   = 101,
  ai_type           = 0,
  give_exp          = 156,
  drop_type         = 75,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 41,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(823, {
  walk_speed        = 0,
  run_speed         = 148,
  scale             = 720,
  r_weapon          = 140,
  l_weapon          = 0,
  level             = 0,
  hp                = 56,
  attack            = 1595,
  hit               = 198,
  def               = 171,
  res               = 147,
  avoid             = 60,
  attack_spd        = 64,
  is_magic_damage   = 102,
  ai_type           = 0,
  give_exp          = 156,
  drop_type         = 78,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 42,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(824, {
  walk_speed        = 0,
  run_speed         = 152,
  scale             = 730,
  r_weapon          = 145,
  l_weapon          = 0,
  level             = 0,
  hp                = 57,
  attack            = 1622,
  hit               = 201,
  def               = 173,
  res               = 150,
  avoid             = 62,
  attack_spd        = 65,
  is_magic_damage   = 103,
  ai_type           = 0,
  give_exp          = 156,
  drop_type         = 83,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 43,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(825, {
  walk_speed        = 0,
  run_speed         = 156,
  scale             = 740,
  r_weapon          = 150,
  l_weapon          = 0,
  level             = 0,
  hp                = 58,
  attack            = 1649,
  hit               = 205,
  def               = 175,
  res               = 153,
  avoid             = 63,
  attack_spd        = 66,
  is_magic_damage   = 104,
  ai_type           = 0,
  give_exp          = 156,
  drop_type         = 89,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 44,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(826, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 750,
  r_weapon          = 155,
  l_weapon          = 0,
  level             = 0,
  hp                = 59,
  attack            = 1677,
  hit               = 209,
  def               = 177,
  res               = 156,
  avoid             = 64,
  attack_spd        = 67,
  is_magic_damage   = 105,
  ai_type           = 0,
  give_exp          = 156,
  drop_type         = 94,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 45,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(827, {
  walk_speed        = 0,
  run_speed         = 164,
  scale             = 760,
  r_weapon          = 160,
  l_weapon          = 0,
  level             = 0,
  hp                = 60,
  attack            = 1704,
  hit               = 213,
  def               = 179,
  res               = 159,
  avoid             = 65,
  attack_spd        = 68,
  is_magic_damage   = 106,
  ai_type           = 0,
  give_exp          = 156,
  drop_type         = 99,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 46,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(828, {
  walk_speed        = 0,
  run_speed         = 168,
  scale             = 770,
  r_weapon          = 165,
  l_weapon          = 0,
  level             = 0,
  hp                = 61,
  attack            = 1731,
  hit               = 217,
  def               = 181,
  res               = 162,
  avoid             = 66,
  attack_spd        = 69,
  is_magic_damage   = 107,
  ai_type           = 0,
  give_exp          = 156,
  drop_type         = 105,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 47,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(829, {
  walk_speed        = 0,
  run_speed         = 172,
  scale             = 780,
  r_weapon          = 170,
  l_weapon          = 0,
  level             = 0,
  hp                = 62,
  attack            = 1759,
  hit               = 221,
  def               = 184,
  res               = 165,
  avoid             = 67,
  attack_spd        = 70,
  is_magic_damage   = 108,
  ai_type           = 0,
  give_exp          = 156,
  drop_type         = 111,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 48,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(830, {
  walk_speed        = 0,
  run_speed         = 176,
  scale             = 790,
  r_weapon          = 175,
  l_weapon          = 0,
  level             = 0,
  hp                = 64,
  attack            = 1814,
  hit               = 228,
  def               = 188,
  res               = 171,
  avoid             = 70,
  attack_spd        = 72,
  is_magic_damage   = 109,
  ai_type           = 0,
  give_exp          = 156,
  drop_type         = 116,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 49,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end