registerNpc(821, {
  walk_speed        = 140,
  run_speed         = 700,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 54,
  hp                = 1542,
  attack            = 190,
  hit               = 166,
  def               = 141,
  res               = 58,
  avoid             = 62,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 156,
  give_exp          = 71,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 40,
  sell_tab0         = 40,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(822, {
  walk_speed        = 144,
  run_speed         = 710,
  scale             = 135,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 55,
  hp                = 1569,
  attack            = 194,
  hit               = 169,
  def               = 144,
  res               = 59,
  avoid             = 63,
  attack_spd        = 101,
  is_magic_damage   = 0,
  ai_type           = 156,
  give_exp          = 75,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 41,
  sell_tab0         = 41,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(823, {
  walk_speed        = 148,
  run_speed         = 720,
  scale             = 140,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 56,
  hp                = 1595,
  attack            = 198,
  hit               = 171,
  def               = 147,
  res               = 60,
  avoid             = 64,
  attack_spd        = 102,
  is_magic_damage   = 0,
  ai_type           = 156,
  give_exp          = 78,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 42,
  sell_tab0         = 42,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(824, {
  walk_speed        = 152,
  run_speed         = 730,
  scale             = 145,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 57,
  hp                = 1622,
  attack            = 201,
  hit               = 173,
  def               = 150,
  res               = 62,
  avoid             = 65,
  attack_spd        = 103,
  is_magic_damage   = 0,
  ai_type           = 156,
  give_exp          = 83,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 43,
  sell_tab0         = 43,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(825, {
  walk_speed        = 156,
  run_speed         = 740,
  scale             = 150,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 58,
  hp                = 1649,
  attack            = 205,
  hit               = 175,
  def               = 153,
  res               = 63,
  avoid             = 66,
  attack_spd        = 104,
  is_magic_damage   = 0,
  ai_type           = 156,
  give_exp          = 89,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 44,
  sell_tab0         = 44,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(826, {
  walk_speed        = 160,
  run_speed         = 750,
  scale             = 155,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 59,
  hp                = 1677,
  attack            = 209,
  hit               = 177,
  def               = 156,
  res               = 64,
  avoid             = 67,
  attack_spd        = 105,
  is_magic_damage   = 0,
  ai_type           = 156,
  give_exp          = 94,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 45,
  sell_tab0         = 45,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(827, {
  walk_speed        = 164,
  run_speed         = 760,
  scale             = 160,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 60,
  hp                = 1704,
  attack            = 213,
  hit               = 179,
  def               = 159,
  res               = 65,
  avoid             = 68,
  attack_spd        = 106,
  is_magic_damage   = 0,
  ai_type           = 156,
  give_exp          = 99,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 46,
  sell_tab0         = 46,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(828, {
  walk_speed        = 168,
  run_speed         = 770,
  scale             = 165,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 61,
  hp                = 1731,
  attack            = 217,
  hit               = 181,
  def               = 162,
  res               = 66,
  avoid             = 69,
  attack_spd        = 107,
  is_magic_damage   = 0,
  ai_type           = 156,
  give_exp          = 105,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 47,
  sell_tab0         = 47,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(829, {
  walk_speed        = 172,
  run_speed         = 780,
  scale             = 170,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 62,
  hp                = 1759,
  attack            = 221,
  hit               = 184,
  def               = 165,
  res               = 67,
  avoid             = 70,
  attack_spd        = 108,
  is_magic_damage   = 0,
  ai_type           = 156,
  give_exp          = 111,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 48,
  sell_tab0         = 48,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(830, {
  walk_speed        = 176,
  run_speed         = 790,
  scale             = 175,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 64,
  hp                = 1814,
  attack            = 228,
  hit               = 188,
  def               = 171,
  res               = 70,
  avoid             = 72,
  attack_spd        = 109,
  is_magic_damage   = 0,
  ai_type           = 156,
  give_exp          = 116,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 49,
  sell_tab0         = 49,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 250,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end