registerNpc(95, {
  walk_speed        = 0,
  run_speed         = 130,
  scale             = 400,
  r_weapon          = 90,
  l_weapon          = 0,
  level             = 0,
  hp                = 18,
  attack            = 999,
  hit               = 1,
  def               = 1,
  res               = 0,
  avoid             = 999,
  attack_spd        = 999,
  is_magic_damage   = 95,
  ai_type           = 0,
  give_exp          = 306,
  drop_type         = 22,
  drop_money        = 142,
  drop_item         = 1,
  union_number      = 1,
  need_summon_count = 60,
  sell_tab0         = 60,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 230,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(97, {
  walk_speed        = 0,
  run_speed         = 180,
  scale             = 520,
  r_weapon          = 98,
  l_weapon          = 0,
  level             = 0,
  hp                = 18,
  attack            = 999,
  hit               = 1,
  def               = 1,
  res               = 0,
  avoid             = 999,
  attack_spd        = 999,
  is_magic_damage   = 110,
  ai_type           = 0,
  give_exp          = 306,
  drop_type         = 22,
  drop_money        = 143,
  drop_item         = 1,
  union_number      = 1,
  need_summon_count = 61,
  sell_tab0         = 61,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 250,
  hit_material_type = 4,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(98, {
  walk_speed        = 0,
  run_speed         = 145,
  scale             = 370,
  r_weapon          = 100,
  l_weapon          = 0,
  level             = 0,
  hp                = 18,
  attack            = 999,
  hit               = 1,
  def               = 1,
  res               = 0,
  avoid             = 999,
  attack_spd        = 999,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 306,
  drop_type         = 22,
  drop_money        = 144,
  drop_item         = 1,
  union_number      = 1,
  need_summon_count = 62,
  sell_tab0         = 62,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 260,
  hit_material_type = 3,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(99, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 400,
  r_weapon          = 96,
  l_weapon          = 0,
  level             = 0,
  hp                = 18,
  attack            = 999,
  hit               = 1,
  def               = 1,
  res               = 0,
  avoid             = 999,
  attack_spd        = 99,
  is_magic_damage   = 120,
  ai_type           = 0,
  give_exp          = 306,
  drop_type         = 22,
  drop_money        = 146,
  drop_item         = 1,
  union_number      = 1,
  need_summon_count = 63,
  sell_tab0         = 63,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 6,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end