registerNpc(607, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 35,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 171,
  drop_type         = 311,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(608, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 40,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 182,
  drop_type         = 312,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(609, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 45,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 186,
  drop_type         = 313,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(610, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 50,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 195,
  drop_type         = 314,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(611, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 55,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 206,
  drop_type         = 315,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(612, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 60,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 210,
  drop_type         = 316,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(613, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 65,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 221,
  drop_type         = 317,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(614, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 70,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 232,
  drop_type         = 318,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(615, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 75,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 236,
  drop_type         = 319,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(616, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 80,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 247,
  drop_type         = 320,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(617, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 85,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 259,
  drop_type         = 321,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

registerNpc(618, {
  walk_speed        = 400,
  run_speed         = 850,
  scale             = 70,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 90,
  hp                = 1,
  attack            = 1,
  hit               = 1,
  def               = 1,
  res               = 1,
  avoid             = 1,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 92,
  give_exp          = 264,
  drop_type         = 322,
  drop_money        = 12,
  drop_item         = 60,
  union_number      = 60,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 220,
  npc_type          = 1,
  hit_material_type = 0,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 1,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end