registerNpc(791, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 90,
  l_weapon          = 0,
  level             = 0,
  hp                = 18,
  attack            = 90,
  hit               = 10,
  def               = 10,
  res               = 50,
  avoid             = 28,
  attack_spd        = 31,
  is_magic_damage   = 110,
  ai_type           = 0,
  give_exp          = 187,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(792, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 95,
  l_weapon          = 0,
  level             = 0,
  hp                = 21,
  attack            = 105,
  hit               = 10,
  def               = 10,
  res               = 55,
  avoid             = 31,
  attack_spd        = 34,
  is_magic_damage   = 108,
  ai_type           = 0,
  give_exp          = 187,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(793, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 100,
  l_weapon          = 0,
  level             = 0,
  hp                = 24,
  attack            = 120,
  hit               = 10,
  def               = 10,
  res               = 60,
  avoid             = 34,
  attack_spd        = 37,
  is_magic_damage   = 106,
  ai_type           = 0,
  give_exp          = 187,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(794, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 105,
  l_weapon          = 0,
  level             = 0,
  hp                = 27,
  attack            = 135,
  hit               = 10,
  def               = 10,
  res               = 65,
  avoid             = 37,
  attack_spd        = 40,
  is_magic_damage   = 104,
  ai_type           = 0,
  give_exp          = 187,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(795, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 110,
  l_weapon          = 0,
  level             = 0,
  hp                = 30,
  attack            = 150,
  hit               = 10,
  def               = 10,
  res               = 70,
  avoid             = 41,
  attack_spd        = 43,
  is_magic_damage   = 102,
  ai_type           = 0,
  give_exp          = 187,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end