registerNpc(791, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 90,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 18,
  hp                = 90,
  attack            = 10,
  hit               = 10,
  def               = 50,
  res               = 28,
  avoid             = 31,
  attack_spd        = 110,
  is_magic_damage   = 0,
  ai_type           = 187,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(792, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 95,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 21,
  hp                = 105,
  attack            = 10,
  hit               = 10,
  def               = 55,
  res               = 31,
  avoid             = 34,
  attack_spd        = 108,
  is_magic_damage   = 0,
  ai_type           = 187,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(793, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 100,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 24,
  hp                = 120,
  attack            = 10,
  hit               = 10,
  def               = 60,
  res               = 34,
  avoid             = 37,
  attack_spd        = 106,
  is_magic_damage   = 0,
  ai_type           = 187,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(794, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 105,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 27,
  hp                = 135,
  attack            = 10,
  hit               = 10,
  def               = 65,
  res               = 37,
  avoid             = 40,
  attack_spd        = 104,
  is_magic_damage   = 0,
  ai_type           = 187,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(795, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 110,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 30,
  hp                = 150,
  attack            = 10,
  hit               = 10,
  def               = 70,
  res               = 41,
  avoid             = 43,
  attack_spd        = 102,
  is_magic_damage   = 0,
  ai_type           = 187,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end