registerNpc(451, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 150,
  l_weapon          = 0,
  level             = 0,
  hp                = 80,
  attack            = 73,
  hit               = 332,
  def               = 204,
  res               = 322,
  avoid             = 232,
  attack_spd        = 67,
  is_magic_damage   = 90,
  ai_type           = 1,
  give_exp          = 181,
  drop_type         = 77,
  drop_money        = 401,
  drop_item         = 92,
  union_number      = 92,
  need_summon_count = 80,
  sell_tab0         = 80,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 18,
  height            = 0
});
registerNpc(452, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 160,
  l_weapon          = 0,
  level             = 0,
  hp                = 88,
  attack            = 75,
  hit               = 367,
  def               = 223,
  res               = 429,
  avoid             = 260,
  attack_spd        = 75,
  is_magic_damage   = 90,
  ai_type           = 1,
  give_exp          = 182,
  drop_type         = 91,
  drop_money        = 402,
  drop_item         = 92,
  union_number      = 92,
  need_summon_count = 80,
  sell_tab0         = 80,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 18,
  height            = 0
});
registerNpc(453, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 170,
  l_weapon          = 0,
  level             = 0,
  hp                = 100,
  attack            = 77,
  hit               = 422,
  def               = 252,
  res               = 664,
  avoid             = 305,
  attack_spd        = 87,
  is_magic_damage   = 90,
  ai_type           = 1,
  give_exp          = 183,
  drop_type         = 102,
  drop_money        = 403,
  drop_item         = 93,
  union_number      = 93,
  need_summon_count = 80,
  sell_tab0         = 80,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 18,
  height            = 0
});
registerNpc(454, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 180,
  l_weapon          = 0,
  level             = 0,
  hp                = 108,
  attack            = 79,
  hit               = 460,
  def               = 273,
  res               = 750,
  avoid             = 336,
  attack_spd        = 95,
  is_magic_damage   = 90,
  ai_type           = 1,
  give_exp          = 184,
  drop_type         = 117,
  drop_money        = 404,
  drop_item         = 93,
  union_number      = 93,
  need_summon_count = 80,
  sell_tab0         = 80,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 18,
  height            = 0
});
registerNpc(455, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 186,
  l_weapon          = 0,
  level             = 0,
  hp                = 120,
  attack            = 82,
  hit               = 517,
  def               = 304,
  res               = 890,
  avoid             = 384,
  attack_spd        = 109,
  is_magic_damage   = 90,
  ai_type           = 1,
  give_exp          = 185,
  drop_type         = 127,
  drop_money        = 405,
  drop_item         = 94,
  union_number      = 94,
  need_summon_count = 80,
  sell_tab0         = 80,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 18,
  height            = 0
});
registerNpc(456, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 192,
  l_weapon          = 0,
  level             = 0,
  hp                = 128,
  attack            = 83,
  hit               = 556,
  def               = 325,
  res               = 991,
  avoid             = 417,
  attack_spd        = 118,
  is_magic_damage   = 90,
  ai_type           = 1,
  give_exp          = 186,
  drop_type         = 132,
  drop_money        = 406,
  drop_item         = 94,
  union_number      = 94,
  need_summon_count = 80,
  sell_tab0         = 80,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 18,
  height            = 0
});
registerNpc(457, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 198,
  l_weapon          = 0,
  level             = 0,
  hp                = 140,
  attack            = 86,
  hit               = 615,
  def               = 358,
  res               = 1154,
  avoid             = 469,
  attack_spd        = 132,
  is_magic_damage   = 90,
  ai_type           = 1,
  give_exp          = 186,
  drop_type         = 142,
  drop_money        = 407,
  drop_item         = 95,
  union_number      = 95,
  need_summon_count = 80,
  sell_tab0         = 80,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 10,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 18,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end