registerNpc(451, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 150,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 80,
  hp                = 73,
  attack            = 332,
  hit               = 204,
  def               = 322,
  res               = 232,
  avoid             = 67,
  attack_spd        = 90,
  is_magic_damage   = 1,
  ai_type           = 181,
  give_exp          = 77,
  drop_type         = 401,
  drop_money        = 92,
  drop_item         = 80,
  union_number      = 80,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 10,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(452, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 160,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 88,
  hp                = 75,
  attack            = 367,
  hit               = 223,
  def               = 429,
  res               = 260,
  avoid             = 75,
  attack_spd        = 90,
  is_magic_damage   = 1,
  ai_type           = 182,
  give_exp          = 91,
  drop_type         = 402,
  drop_money        = 92,
  drop_item         = 80,
  union_number      = 80,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 10,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(453, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 170,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 100,
  hp                = 77,
  attack            = 422,
  hit               = 252,
  def               = 664,
  res               = 305,
  avoid             = 87,
  attack_spd        = 90,
  is_magic_damage   = 1,
  ai_type           = 183,
  give_exp          = 102,
  drop_type         = 403,
  drop_money        = 93,
  drop_item         = 80,
  union_number      = 80,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 10,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(454, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 180,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 108,
  hp                = 79,
  attack            = 460,
  hit               = 273,
  def               = 750,
  res               = 336,
  avoid             = 95,
  attack_spd        = 90,
  is_magic_damage   = 1,
  ai_type           = 184,
  give_exp          = 117,
  drop_type         = 404,
  drop_money        = 93,
  drop_item         = 80,
  union_number      = 80,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 10,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(455, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 186,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 120,
  hp                = 82,
  attack            = 517,
  hit               = 304,
  def               = 890,
  res               = 384,
  avoid             = 109,
  attack_spd        = 90,
  is_magic_damage   = 1,
  ai_type           = 185,
  give_exp          = 127,
  drop_type         = 405,
  drop_money        = 94,
  drop_item         = 80,
  union_number      = 80,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 10,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(456, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 192,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 128,
  hp                = 83,
  attack            = 556,
  hit               = 325,
  def               = 991,
  res               = 417,
  avoid             = 118,
  attack_spd        = 90,
  is_magic_damage   = 1,
  ai_type           = 186,
  give_exp          = 132,
  drop_type         = 406,
  drop_money        = 94,
  drop_item         = 80,
  union_number      = 80,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 10,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(457, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 198,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 140,
  hp                = 86,
  attack            = 615,
  hit               = 358,
  def               = 1154,
  res               = 469,
  avoid             = 132,
  attack_spd        = 90,
  is_magic_damage   = 1,
  ai_type           = 186,
  give_exp          = 142,
  drop_type         = 407,
  drop_money        = 95,
  drop_item         = 80,
  union_number      = 80,
  need_summon_count = 0,
  sell_tab0         = 0,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 10,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end