registerNpc(871, {
  walk_speed        = 160,
  run_speed         = 370,
  scale             = 160,
  r_weapon          = 112,
  l_weapon          = 0,
  level             = 69,
  hp                = 2000,
  attack            = 224,
  hit               = 183,
  def               = 190,
  res               = 84,
  avoid             = 71,
  attack_spd        = 100,
  is_magic_damage   = 0,
  ai_type           = 161,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 76,
  sell_tab0         = 76,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(872, {
  walk_speed        = 165,
  run_speed         = 380,
  scale             = 166,
  r_weapon          = 112,
  l_weapon          = 0,
  level             = 71,
  hp                = 2050,
  attack            = 231,
  hit               = 187,
  def               = 194,
  res               = 87,
  avoid             = 73,
  attack_spd        = 101,
  is_magic_damage   = 0,
  ai_type           = 161,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 77,
  sell_tab0         = 77,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(873, {
  walk_speed        = 170,
  run_speed         = 390,
  scale             = 172,
  r_weapon          = 112,
  l_weapon          = 0,
  level             = 73,
  hp                = 2100,
  attack            = 238,
  hit               = 192,
  def               = 198,
  res               = 90,
  avoid             = 76,
  attack_spd        = 102,
  is_magic_damage   = 0,
  ai_type           = 161,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 78,
  sell_tab0         = 78,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(874, {
  walk_speed        = 175,
  run_speed         = 400,
  scale             = 178,
  r_weapon          = 113,
  l_weapon          = 0,
  level             = 75,
  hp                = 2150,
  attack            = 246,
  hit               = 196,
  def               = 202,
  res               = 93,
  avoid             = 78,
  attack_spd        = 103,
  is_magic_damage   = 0,
  ai_type           = 161,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 79,
  sell_tab0         = 79,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(875, {
  walk_speed        = 180,
  run_speed         = 410,
  scale             = 184,
  r_weapon          = 113,
  l_weapon          = 0,
  level             = 77,
  hp                = 2200,
  attack            = 253,
  hit               = 200,
  def               = 206,
  res               = 95,
  avoid             = 80,
  attack_spd        = 104,
  is_magic_damage   = 0,
  ai_type           = 161,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 80,
  sell_tab0         = 80,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(876, {
  walk_speed        = 185,
  run_speed         = 420,
  scale             = 190,
  r_weapon          = 113,
  l_weapon          = 0,
  level             = 79,
  hp                = 2250,
  attack            = 261,
  hit               = 205,
  def               = 210,
  res               = 98,
  avoid             = 82,
  attack_spd        = 105,
  is_magic_damage   = 0,
  ai_type           = 161,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 81,
  sell_tab0         = 81,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(877, {
  walk_speed        = 190,
  run_speed         = 430,
  scale             = 196,
  r_weapon          = 113,
  l_weapon          = 0,
  level             = 81,
  hp                = 2300,
  attack            = 268,
  hit               = 209,
  def               = 214,
  res               = 101,
  avoid             = 84,
  attack_spd        = 106,
  is_magic_damage   = 0,
  ai_type           = 161,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 82,
  sell_tab0         = 82,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(878, {
  walk_speed        = 195,
  run_speed         = 440,
  scale             = 202,
  r_weapon          = 114,
  l_weapon          = 0,
  level             = 83,
  hp                = 2350,
  attack            = 276,
  hit               = 213,
  def               = 218,
  res               = 104,
  avoid             = 86,
  attack_spd        = 107,
  is_magic_damage   = 0,
  ai_type           = 161,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 83,
  sell_tab0         = 83,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(879, {
  walk_speed        = 200,
  run_speed         = 450,
  scale             = 208,
  r_weapon          = 114,
  l_weapon          = 0,
  level             = 85,
  hp                = 2400,
  attack            = 284,
  hit               = 218,
  def               = 222,
  res               = 107,
  avoid             = 89,
  attack_spd        = 108,
  is_magic_damage   = 0,
  ai_type           = 161,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 84,
  sell_tab0         = 84,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

registerNpc(880, {
  walk_speed        = 205,
  run_speed         = 460,
  scale             = 214,
  r_weapon          = 115,
  l_weapon          = 0,
  level             = 88,
  hp                = 2450,
  attack            = 295,
  hit               = 225,
  def               = 226,
  res               = 111,
  avoid             = 92,
  attack_spd        = 109,
  is_magic_damage   = 0,
  ai_type           = 161,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 85,
  sell_tab0         = 85,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 300,
  npc_type          = 0,
  hit_material_type = 2,
  face_icon         = 0,
  summon_mob_type   = 0,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end