registerNpc(871, {
  walk_speed        = 0,
  run_speed         = 160,
  scale             = 370,
  r_weapon          = 160,
  l_weapon          = 112,
  level             = 0,
  hp                = 69,
  attack            = 2000,
  hit               = 224,
  def               = 183,
  res               = 190,
  avoid             = 84,
  attack_spd        = 71,
  is_magic_damage   = 100,
  ai_type           = 0,
  give_exp          = 161,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 76,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(872, {
  walk_speed        = 0,
  run_speed         = 165,
  scale             = 380,
  r_weapon          = 166,
  l_weapon          = 112,
  level             = 0,
  hp                = 71,
  attack            = 2050,
  hit               = 231,
  def               = 187,
  res               = 194,
  avoid             = 87,
  attack_spd        = 73,
  is_magic_damage   = 101,
  ai_type           = 0,
  give_exp          = 161,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 77,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(873, {
  walk_speed        = 0,
  run_speed         = 170,
  scale             = 390,
  r_weapon          = 172,
  l_weapon          = 112,
  level             = 0,
  hp                = 73,
  attack            = 2100,
  hit               = 238,
  def               = 192,
  res               = 198,
  avoid             = 90,
  attack_spd        = 76,
  is_magic_damage   = 102,
  ai_type           = 0,
  give_exp          = 161,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 78,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(874, {
  walk_speed        = 0,
  run_speed         = 175,
  scale             = 400,
  r_weapon          = 178,
  l_weapon          = 113,
  level             = 0,
  hp                = 75,
  attack            = 2150,
  hit               = 246,
  def               = 196,
  res               = 202,
  avoid             = 93,
  attack_spd        = 78,
  is_magic_damage   = 103,
  ai_type           = 0,
  give_exp          = 161,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 79,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(875, {
  walk_speed        = 0,
  run_speed         = 180,
  scale             = 410,
  r_weapon          = 184,
  l_weapon          = 113,
  level             = 0,
  hp                = 77,
  attack            = 2200,
  hit               = 253,
  def               = 200,
  res               = 206,
  avoid             = 95,
  attack_spd        = 80,
  is_magic_damage   = 104,
  ai_type           = 0,
  give_exp          = 161,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 80,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(876, {
  walk_speed        = 0,
  run_speed         = 185,
  scale             = 420,
  r_weapon          = 190,
  l_weapon          = 113,
  level             = 0,
  hp                = 79,
  attack            = 2250,
  hit               = 261,
  def               = 205,
  res               = 210,
  avoid             = 98,
  attack_spd        = 82,
  is_magic_damage   = 105,
  ai_type           = 0,
  give_exp          = 161,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 81,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(877, {
  walk_speed        = 0,
  run_speed         = 190,
  scale             = 430,
  r_weapon          = 196,
  l_weapon          = 113,
  level             = 0,
  hp                = 81,
  attack            = 2300,
  hit               = 268,
  def               = 209,
  res               = 214,
  avoid             = 101,
  attack_spd        = 84,
  is_magic_damage   = 106,
  ai_type           = 0,
  give_exp          = 161,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 82,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(878, {
  walk_speed        = 0,
  run_speed         = 195,
  scale             = 440,
  r_weapon          = 202,
  l_weapon          = 114,
  level             = 0,
  hp                = 83,
  attack            = 2350,
  hit               = 276,
  def               = 213,
  res               = 218,
  avoid             = 104,
  attack_spd        = 86,
  is_magic_damage   = 107,
  ai_type           = 0,
  give_exp          = 161,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 83,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(879, {
  walk_speed        = 0,
  run_speed         = 200,
  scale             = 450,
  r_weapon          = 208,
  l_weapon          = 114,
  level             = 0,
  hp                = 85,
  attack            = 2400,
  hit               = 284,
  def               = 218,
  res               = 222,
  avoid             = 107,
  attack_spd        = 89,
  is_magic_damage   = 108,
  ai_type           = 0,
  give_exp          = 161,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 84,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
registerNpc(880, {
  walk_speed        = 0,
  run_speed         = 205,
  scale             = 460,
  r_weapon          = 214,
  l_weapon          = 115,
  level             = 0,
  hp                = 88,
  attack            = 2450,
  hit               = 295,
  def               = 225,
  res               = 226,
  avoid             = 111,
  attack_spd        = 92,
  is_magic_damage   = 109,
  ai_type           = 0,
  give_exp          = 161,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 85,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 300,
  hit_material_type = 0,
  face_icon         = 2,
  summon_mob_type   = 2,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end