registerNpc(771, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 90,
  l_weapon          = 0,
  level             = 0,
  hp                = 15,
  attack            = 75,
  hit               = 10,
  def               = 10,
  res               = 50,
  avoid             = 26,
  attack_spd        = 28,
  is_magic_damage   = 110,
  ai_type           = 0,
  give_exp          = 176,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 40,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(772, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 95,
  l_weapon          = 0,
  level             = 0,
  hp                = 20,
  attack            = 100,
  hit               = 10,
  def               = 10,
  res               = 55,
  avoid             = 28,
  attack_spd        = 31,
  is_magic_damage   = 108,
  ai_type           = 0,
  give_exp          = 177,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 40,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(773, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 100,
  l_weapon          = 0,
  level             = 0,
  hp                = 25,
  attack            = 125,
  hit               = 10,
  def               = 10,
  res               = 60,
  avoid             = 31,
  attack_spd        = 34,
  is_magic_damage   = 106,
  ai_type           = 0,
  give_exp          = 178,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 40,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(774, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 105,
  l_weapon          = 0,
  level             = 0,
  hp                = 30,
  attack            = 150,
  hit               = 10,
  def               = 10,
  res               = 65,
  avoid             = 34,
  attack_spd        = 37,
  is_magic_damage   = 104,
  ai_type           = 0,
  give_exp          = 179,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 40,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(775, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 110,
  l_weapon          = 0,
  level             = 0,
  hp                = 35,
  attack            = 175,
  hit               = 10,
  def               = 10,
  res               = 70,
  avoid             = 37,
  attack_spd        = 40,
  is_magic_damage   = 102,
  ai_type           = 0,
  give_exp          = 180,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 40,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end