registerNpc(781, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 100,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 25,
  hp                = 125,
  attack            = 10,
  hit               = 10,
  def               = 999,
  res               = 999,
  avoid             = 999,
  attack_spd        = 110,
  is_magic_damage   = 0,
  ai_type           = 170,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(782, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 110,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 25,
  hp                = 125,
  attack            = 10,
  hit               = 10,
  def               = 999,
  res               = 999,
  avoid             = 999,
  attack_spd        = 108,
  is_magic_damage   = 0,
  ai_type           = 171,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(783, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 120,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 25,
  hp                = 125,
  attack            = 10,
  hit               = 10,
  def               = 999,
  res               = 999,
  avoid             = 999,
  attack_spd        = 106,
  is_magic_damage   = 0,
  ai_type           = 172,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(784, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 130,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 25,
  hp                = 125,
  attack            = 10,
  hit               = 10,
  def               = 999,
  res               = 999,
  avoid             = 999,
  attack_spd        = 104,
  is_magic_damage   = 0,
  ai_type           = 173,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

registerNpc(785, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 140,
  r_weapon          = 0,
  l_weapon          = 0,
  level             = 25,
  hp                = 125,
  attack            = 10,
  hit               = 10,
  def               = 999,
  res               = 999,
  avoid             = 999,
  attack_spd        = 102,
  is_magic_damage   = 0,
  ai_type           = 174,
  give_exp          = 0,
  drop_type         = 3,
  drop_money        = 0,
  drop_item         = 100,
  union_number      = 100,
  need_summon_count = 50,
  sell_tab0         = 50,
  sell_tab1         = 0,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 1,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});

function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end