registerNpc(781, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 100,
  l_weapon          = 0,
  level             = 0,
  hp                = 25,
  attack            = 125,
  hit               = 10,
  def               = 10,
  res               = 999,
  avoid             = 999,
  attack_spd        = 999,
  is_magic_damage   = 110,
  ai_type           = 0,
  give_exp          = 170,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(782, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 110,
  l_weapon          = 0,
  level             = 0,
  hp                = 25,
  attack            = 125,
  hit               = 10,
  def               = 10,
  res               = 999,
  avoid             = 999,
  attack_spd        = 999,
  is_magic_damage   = 108,
  ai_type           = 0,
  give_exp          = 171,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(783, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 120,
  l_weapon          = 0,
  level             = 0,
  hp                = 25,
  attack            = 125,
  hit               = 10,
  def               = 10,
  res               = 999,
  avoid             = 999,
  attack_spd        = 999,
  is_magic_damage   = 106,
  ai_type           = 0,
  give_exp          = 172,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(784, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 130,
  l_weapon          = 0,
  level             = 0,
  hp                = 25,
  attack            = 125,
  hit               = 10,
  def               = 10,
  res               = 999,
  avoid             = 999,
  attack_spd        = 999,
  is_magic_damage   = 104,
  ai_type           = 0,
  give_exp          = 173,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
registerNpc(785, {
  walk_speed        = 0,
  run_speed         = 0,
  scale             = 0,
  r_weapon          = 140,
  l_weapon          = 0,
  level             = 0,
  hp                = 25,
  attack            = 125,
  hit               = 10,
  def               = 10,
  res               = 999,
  avoid             = 999,
  attack_spd        = 999,
  is_magic_damage   = 102,
  ai_type           = 0,
  give_exp          = 174,
  drop_type         = 0,
  drop_money        = 3,
  drop_item         = 0,
  union_number      = 0,
  need_summon_count = 100,
  sell_tab0         = 100,
  sell_tab1         = 50,
  sell_tab2         = 0,
  sell_tab3         = 0,
  can_target        = 0,
  attack_range      = 0,
  npc_type          = 0,
  hit_material_type = 0,
  face_icon         = 1,
  summon_mob_type   = 1,
  quest_type        = 0,
  height            = 0
});
function OnInit(entity)
  return true
end

function OnCreate(entity)
  return true
end

function OnDelete(entity)
  return true
end

function OnDead(entity)
end

function OnDamaged(entity)
end