set(SQLPP11_INSTALL_DIR ${CMAKE_THIRD_PARTY_DIR})
set(CMAKE_INSTALL_PREFIX ${CMAKE_THIRD_PARTY_DIR})
set(INSTALL_PLUGINDIR ${CMAKE_INSTALL_PREFIX})

FetchContent_Declare(
  sqlpp11
  GIT_REPOSITORY https://github.com/rbock/sqlpp11
  GIT_TAG 0.65
)

# sqlpp11 settings
set(BUILD_MYSQL_CONNECTOR OFF)
set(BUILD_MARIADB_CONNECTOR ON)
set(BUILD_POSTGRESQL_CONNECTOR OFF)
set(BUILD_SQLITE3_CONNECTOR ON)
set(SQLPP11_INSTALL OFF CACHE BOOL "" FORCE)
set(CMAKE_SKIP_INSTALL_RULES TRUE)

FetchContent_MakeAvailable(sqlpp11)