set(SQLPP11_INSTALL_DIR ${CMAKE_THIRD_PARTY_DIR})

if(HAVE_SQLPP11_TEMPLATE_SUPPORT_PATCHED)
  ExternalProject_Add(
    sqlpp11
    GIT_REPOSITORY https://github.com/rbock/sqlpp11
    GIT_TAG c729387ab66b19acdff02f047660bdda8f75b343
    CMAKE_ARGS -G ${CMAKE_GENERATOR} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DHinnantDate_INCLUDE_DIR=${DATE_INCLUDE_DIR} -DCMAKE_INSTALL_PREFIX=${SQLPP11_INSTALL_DIR} -DENABLE_TESTS=OFF
    PATCH_COMMAND ${PATCH_SCRIPT_PATH} ${CMAKE_PATCH_DIR}/sqlpp11_template.patch
    INSTALL_DIR ${SQLPP11_INSTALL_DIR}
    DEPENDS DATE::DATE
  )
else()
  ExternalProject_Add(
    sqlpp11
    GIT_REPOSITORY https://github.com/rbock/sqlpp11
    GIT_TAG c729387ab66b19acdff02f047660bdda8f75b343
    CMAKE_ARGS -G ${CMAKE_GENERATOR} -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE} -DHinnantDate_INCLUDE_DIR=${DATE_INCLUDE_DIR} -DCMAKE_INSTALL_PREFIX=${SQLPP11_INSTALL_DIR} -DENABLE_TESTS=OFF
    PATCH_COMMAND ${PATCH_SCRIPT_PATH} ${CMAKE_PATCH_DIR}/sqlpp11_ddl2cpp_mediumint_unsigned.patch
    INSTALL_DIR ${SQLPP11_INSTALL_DIR}
    DEPENDS DATE::DATE
  )
endif()

ExternalProject_Get_Property(
  sqlpp11
  install_dir
)

set(SQLPP11_EXE_PATH "${install_dir}/bin/sqlpp11-ddl2cpp")
set(SQLPP11_INCLUDE_DIR "${install_dir}/include")
if(NOT TARGET SQLPP11::SQLPP11)
  add_library(SQLPP11::SQLPP11 INTERFACE IMPORTED)
  add_dependencies(SQLPP11::SQLPP11 sqlpp11)
  set_target_properties(SQLPP11::SQLPP11 PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${SQLPP11_INCLUDE_DIR}")
endif()