#------------------------------------------------------------------------------
# Google Crashpad
#
# Upstream crashpad can only be built with depot_tools + gn, which is what made
# the old gn/ninja ExternalProject so brittle. We use the getsentry fork
# instead: identical crashpad sources, but its third_party deps are plain git
# submodules and every BUILD.gn has a hand-written CMakeLists next to it, so it
# drops straight into FetchContent.
#------------------------------------------------------------------------------

# Pin an exact commit. The fork carries no release tags, and its CMake files
# are regenerated by hand whenever it is rebased onto upstream, so "latest" is
# not a safe moving target.
set(CRASHPAD_GIT_TAG aac2dcd0c093e39eec4f571ad3e79605847c5b93)

# crashpad's own cache options, set before MakeAvailable so its option() calls
# see these instead of their defaults.
#
# Installation stays off: we do not want crashpad's static libs or headers in
# our install tree, only the handler executable (installed explicitly below).
set(CRASHPAD_ENABLE_INSTALL OFF CACHE BOOL "" FORCE)
set(CRASHPAD_ENABLE_INSTALL_DEV OFF CACHE BOOL "" FORCE)
set(CRASHPAD_ENABLE_STACKTRACE OFF CACHE BOOL "" FORCE)

# Prefer the system zlib that the top level CMakeLists already looks for, and
# fall back to crashpad's bundled copy when there is none.
if (ZLIB_FOUND)
  set(CRASHPAD_ZLIB_SYSTEM ON CACHE BOOL "" FORCE)
else ()
  set(CRASHPAD_ZLIB_SYSTEM OFF CACHE BOOL "" FORCE)
endif ()

FetchContent_Declare(
    crashpad
    GIT_REPOSITORY https://github.com/getsentry/crashpad.git
    GIT_TAG ${CRASHPAD_GIT_TAG}
    GIT_SUBMODULES_RECURSE TRUE
)

FetchContent_MakeAvailable(crashpad)

#------------------------------------------------------------------------------
# One target for everything a crashpad *client* needs.
#
# crashpad::client already pulls in compat/util/mini_chromium publicly; the
# include directories are repeated here as SYSTEM so crashpad's own headers do
# not trip our warning flags.
#------------------------------------------------------------------------------
if (NOT TARGET utils::crashpad)
  add_library(utils_crashpad INTERFACE)
  target_link_libraries(utils_crashpad
      INTERFACE
      crashpad::client
      )
  # crashpad headers are included repo-root relative ("client/crashpad_client.h")
  # and its base/ headers come from mini_chromium.
  target_include_directories(utils_crashpad
      SYSTEM INTERFACE
      ${crashpad_SOURCE_DIR}
      ${crashpad_SOURCE_DIR}/third_party/mini_chromium/mini_chromium
      )
  add_library(utils::crashpad ALIAS utils_crashpad)
endif ()

#------------------------------------------------------------------------------
# The out-of-process handler.
#
# This is the big behavioural difference from breakpad: crashpad does not write
# the minidump from inside the crashing process, it execs this binary. So the
# handler has to sit next to the servers at runtime and ship in the install
# tree, otherwise CrashReport silently has nothing to start.
#------------------------------------------------------------------------------
set(CRASHPAD_HANDLER_NAME crashpad_handler)

set_target_properties(crashpad_handler PROPERTIES
    RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/bin
    FOLDER "3rdparty"
    )

# crashpad installs the handler itself, but without a COMPONENT, so a
# component-scoped `cmake --install --component Runtime` would skip it.
install(PROGRAMS $<TARGET_FILE:crashpad_handler>
    DESTINATION bin
    COMPONENT Runtime)
