set(SQLPP11_INSTALL_DIR ${CMAKE_THIRD_PARTY_DIR})
set(CMAKE_INSTALL_PREFIX ${CMAKE_THIRD_PARTY_DIR})
set(INSTALL_PLUGINDIR ${CMAKE_INSTALL_PREFIX})

FetchContent_Declare(
  sqlpp11
  GIT_REPOSITORY https://github.com/rbock/sqlpp11
  GIT_TAG a50d71936465c26abc9093ed3b87059fe72aa711
)

# sqlpp11 settings
set(BUILD_MYSQL_CONNECTOR ON)
set(BUILD_SQLITE3_CONNECTOR ON)

FetchContent_MakeAvailable(sqlpp11)