MACRO(OSIROSE_CONFIGURE_FILE_AUTOTOOLS_COMPAT)
  SET(configure_input "${ARGV1} generated from ${ARGV0} by CMake.")
  CONFIGURE_FILE(${ARGV})
ENDMACRO(OSIROSE_CONFIGURE_FILE_AUTOTOOLS_COMPAT)

MESSAGE(STATUS "osIROSE CMake Tools loaded.")
